// GENERATED by scripts/gen-doms-swift.mjs — DO NOT EDIT BY HAND.
//
// Source of truth:
//   · DOMS_MUSCLES, DOMS_LEVELS           src/lib/hooks/useRecovery.ts
//   · DOMS_TO_LANDMARK                    src/lib/body/atlas.ts
//   · SUB_REGIONS, JOINTS, SORENESS_SIDES src/lib/body/subRegions.ts
//
// Re-run `npm run doms` after changing any of those. `npm run check:doms`
// fails if this file is stale, and it is part of `npm run check`.

import OnyxCore

/// The soreness vocabularies, mirrored from the web.
///
/// The GROUP is what a user rates (a sore arm is a sore arm); the landmarks are
/// what the figure draws; the sub-region is optional detail the scoring engine
/// never reads. Severity 0…3 becomes intensity 0…1 because the atlas draws
/// AMOUNT and passes no verdicts.
enum DomsMap {

    /// Display order: upper, trunk, lower — as the web lists them.
    static let muscles = ["Chest", "Back", "Arms", "Shoulders", "Abs", "Glutes", "Quads", "Hamstrings", "Inner thighs", "Calves"]

    /// Index IS the stored severity.
    static let levels = ["None", "Mild", "Moderate", "Severe"]

    static let maxSeverity = 3

    /// Stored `side` values. `both` is the default and the pre-v2 meaning.
    static let sides = ["both", "left", "right"]

    /// Non-muscle complaint points. Never scored, never a landmark.
    static let joints = ["Knee", "Hip", "Ankle", "Wrist", "Elbow", "AC joint", "Lumbar junction", "Neck"]

    /// Sub-regions of the muscles that have them. A muscle absent here is
    /// always rated whole; a muscle present here may still be rated whole.
    static let subRegions: [String: [String]] = [
        "Back": ["Traps", "Rhomboids", "Lats", "Erectors"],
        "Arms": ["Biceps", "Triceps", "Forearms"],
        "Shoulders": ["Front delts", "Side delts", "Rear delts"],
        "Inner thighs": ["Adductors", "Abductors"],
    ]

    static let landmarks: [String: [LandmarkMuscle]] = [
        "Chest": [.chest],
        "Back": [.lats, .upperBack, .lowerBack],
        "Arms": [.biceps, .triceps, .forearms],
        "Shoulders": [.frontDelts, .sideDelts, .rearDelts],
        "Abs": [.absCore],
        "Glutes": [.glutes],
        "Quads": [.quads],
        "Hamstrings": [.hamstrings],
        "Inner thighs": [.adductors],
        "Calves": [.calves],
    ]

    /// The muscle a sub-region belongs to — the fold that keeps the ten intact.
    static let parentOfSubRegion: [String: String] = subRegions.reduce(into: [:]) { out, pair in
        for sub in pair.value { out[sub] = pair.key }
    }

    /// `domsToWorked` — group → severity becomes landmark → 0…1, max-merged.
    static func worked(_ severity: [String: Int]) -> [LandmarkMuscle: Double] {
        var out: [LandmarkMuscle: Double] = [:]
        for (muscle, s) in severity where s > 0 {
            let intensity = min(1, max(0, Double(s) / Double(maxSeverity)))
            for landmark in landmarks[muscle] ?? [] {
                out[landmark] = max(out[landmark] ?? 0, intensity)
            }
        }
        return out
    }

    /// "Quads moderate · Chest mild", in display order; nil when nothing is sore.
    static func summary(_ severity: [String: Int]) -> String? {
        let sore = muscles.compactMap { m -> String? in
            guard let s = severity[m], s > 0, s < levels.count else { return nil }
            return "\(m) \(levels[s].lowercased())"
        }
        return sore.isEmpty ? nil : sore.joined(separator: " · ")
    }
}

extension DomsMap {
    /// The group a landmark belongs to — the reverse of `landmarks`, which is
    /// what a tap on the body needs: the atlas answers in landmarks (sixteen)
    /// and soreness is rated in groups (ten).
    static let groupOfLandmark: [LandmarkMuscle: String] = landmarks.reduce(into: [:]) { out, pair in
        for landmark in pair.value { out[landmark] = pair.key }
    }

    static func group(of landmark: LandmarkMuscle) -> String? { groupOfLandmark[landmark] }
}
