import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { generate, TARGETS } from '../../scripts/gen-doms-swift.mjs'
import { DOMS_MUSCLES } from '@/lib/hooks/useRecovery'
import { ALL_SUB_REGIONS, JOINTS, SORENESS_SIDES } from '@/lib/body/subRegions'

/**
 * ONE soreness vocabulary, two platforms.
 *
 * Until this test existed there was no check of any kind between `DOMS_MUSCLES`
 * and `DomsMap.swift` — the Swift list was hand-typed, and `AtlasHitTests` only
 * asserted its landmarks were a SUBSET of the sixteen, which is an assertion
 * that passes when a muscle is missing. That is precisely how the adductors
 * ended up drawn on the figure with no rating able to reach them, and how
 * `Inner thighs` shipped on the web while iOS still knew nine.
 *
 * v2 adds three more shared vocabularies, so the copy is generated and this is
 * what stops the two separating.
 */
const SWIFT = readFileSync('native/Onyx/Features/Pulse/DomsMap.swift', 'utf8')
const CORE = readFileSync('native/Packages/OnyxCore/Sources/OnyxCore/Training/DomsMuscles.swift', 'utf8')

const sources = {
  recovery: readFileSync('src/lib/recovery/soreness.ts', 'utf8'),
  atlas: readFileSync('src/lib/body/atlas.ts', 'utf8'),
  sub: readFileSync('src/lib/body/subRegions.ts', 'utf8'),
}

describe('the generated Swift DOMS map', () => {
  it('writes the vocabulary to OnyxCore and the atlas join to the app', () => {
    // The scorer lives in OnyxData, which imports OnyxCore and cannot see the
    // app target at all — so the list the fold checks against has to be in the
    // package, and only the view half stays in Features/Pulse.
    expect(TARGETS.core).toMatch(/OnyxCore\/Sources\/OnyxCore\/Training\/DomsMuscles\.swift$/)
    expect(TARGETS.app).toMatch(/native\/Onyx\/Features\/Pulse\/DomsMap\.swift$/)
  })

  it('is exactly what the generator produces from the current vocabularies', () => {
    // The whole contract. If this fails: npm run doms
    const out = generate(sources)
    expect(CORE).toBe(out.core)
    expect(SWIFT).toBe(out.app)
  })

  it('carries every DOMS muscle, so none can be web-only', () => {
    for (const m of DOMS_MUSCLES) expect(CORE).toContain(`"${m}"`)
  })

  it('carries every sub-region, side and joint', () => {
    for (const s of ALL_SUB_REGIONS) expect(CORE).toContain(`"${s}"`)
    for (const s of SORENESS_SIDES) expect(CORE).toContain(`"${s}"`)
    for (const j of JOINTS) expect(CORE).toContain(`"${j}"`)
  })

  it('exposes the recognised set the scorer folds against', () => {
    // `foldDomsSeverity` in OnyxData asks this per row. Without it an
    // unreadable muscle_group would count toward the battery, which is the
    // bug this wave fixes on both platforms at once.
    expect(CORE).toContain('public static let recognised: Set<String>')
    expect(CORE).toContain('public enum DomsMuscles')
  })

  it('says out loud that it is generated', () => {
    // A hand edit to a generated file is lost on the next run, silently. The
    // banner is the only warning a reader gets before that happens.
    expect(SWIFT.startsWith('// GENERATED by')).toBe(true)
    expect(SWIFT).toContain('DO NOT EDIT BY HAND')
    expect(CORE.startsWith('// GENERATED by')).toBe(true)
  })

  it('keeps the API the Pulse views and tests already call', () => {
    // The generator replaced a hand-written file. These are its callers'
    // entry points; losing one is a build break on a target the web gate
    // cannot compile, so it is pinned here where the web gate CAN see it.
    for (const symbol of [
      'static let muscles', 'static let levels', 'static let maxSeverity',
      'static let landmarks', 'static let subRegions', 'static let joints',
      'static let sides', 'static let parentOfSubRegion',
      'func worked(', 'func summary(', 'func group(of',
    ]) {
      expect(SWIFT, `${symbol} went missing`).toContain(symbol)
    }
  })
})
