-- ─────────────────────────────────────────────────────────────────────────────
-- W2 · THE FOUNDER'S SEED — paste AFTER `w2-generic-model.sql`.
--
-- GENERATED by `SeedDumpTests` (native/Packages/OnyxData/Tests) from the Swift
-- constants this wave deletes: `Program.all`, `Phases.all`, `Levers.all` +
-- `Levers.schedule`, `Programs.cutTargets` / `.bulkTargets`, `PhaseGoals`,
-- `PrTruth.floor(for:)` and `Supplements.protocolSeed`. Not one number below
-- was typed by hand; the rows ARE the constants, so the app reads the same
-- deck, targets, phase, lever, stack and PR floors the day after as the day
-- before.
--
-- SCOPED TO ONE ACCOUNT. Every statement names the founder's user_id. The
-- second account (created 2026-09-08) is a fresh user and gets nothing here;
-- W5's onboarding seeds a new user from `plan-templates.json` instead.
--
-- IDEMPOTENT, AND IT NEVER OVERWRITES AN EDIT. Inserts are `on conflict do
-- nothing` or `where not exists`; the two tables that already hold founder
-- rows (`plan_phase_goals`, `target_profiles`) are merged with `coalesce`, so
-- a figure the founder changed in the app (the cut is 1,935 kcal / 190 g C in
-- the row, not the constant's 1,955 / 195) stays what they made it, and only
-- a NULL column takes the constant's value. `custom_supplements` are inserted
-- only where the item key is absent — all nine already exist, and the live
-- L-Citrulline dose (6 g) differs from the seed's (3 g) on purpose. Do not
-- turn that into `on conflict do update`.
--
-- PR FLOORS are `PrTruth.floor(for:)` — the book's excess over what Onyx's own
-- history already reached, NOT the raw book — written as `personal_records`
-- rows with no session, and only where they exceed the row already there.
-- ─────────────────────────────────────────────────────────────────────────────

begin;

-- ── 1 · plans — the picker's three entries ─────────────────────────────────
update public.plans
   set name = 'Onyx-5', blurb = '5-day antagonist hybrid — Sun/Mon/Tue/Thu/Fri, Wed & Sat Zone-2 rest.', is_legacy = false, sort = 0,
       started_on = coalesce(started_on, '2026-07-15')
 where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and program_id = 'onyx5';
insert into public.plans (user_id, name, program_id, active, started_on, blurb, is_legacy, sort)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Onyx-5', 'onyx5', false, '2026-07-15', '5-day antagonist hybrid — Sun/Mon/Tue/Thu/Fri, Wed & Sat Zone-2 rest.', false, 0
 where not exists (select 1 from public.plans where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and program_id = 'onyx5');
update public.plans
   set name = 'Onyx-4', blurb = '4-day upper/lower backup — Mon/Tue/Thu/Fri. Bulk adds volume; cut trims it.', is_legacy = false, sort = 1,
       started_on = coalesce(started_on, null)
 where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and program_id = 'onyx4';
insert into public.plans (user_id, name, program_id, active, started_on, blurb, is_legacy, sort)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Onyx-4', 'onyx4', false, null, '4-day upper/lower backup — Mon/Tue/Thu/Fri. Bulk adds volume; cut trims it.', false, 1
 where not exists (select 1 from public.plans where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and program_id = 'onyx4');
update public.plans
   set name = 'Push/Pull/Legs', blurb = 'Historical Push/Pull/Legs — Sun/Thu Push · Mon/Fri Pull · Tue Legs · Wed & Sat rest.', is_legacy = true, sort = 2,
       started_on = coalesce(started_on, '2026-03-08')
 where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and program_id = 'ppl';
insert into public.plans (user_id, name, program_id, active, started_on, blurb, is_legacy, sort)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Push/Pull/Legs', 'ppl', false, '2026-03-08', 'Historical Push/Pull/Legs — Sun/Thu Push · Mon/Fri Pull · Tue Legs · Wed & Sat rest.', true, 2
 where not exists (select 1 from public.plans where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and program_id = 'ppl');

-- ── 2 · routines — the three decks, one row per program day ────────────────
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cb_a', 'Upper A', 'Chest + Back', 0, 14708796, 0,
        '{"exercises":[{"compound":true,"cutSets":3,"exerciseId":"d1bb00f2-f88d-4a6c-80b1-e6cd6f9136a2","name":"Incline DB Press","reps":"8–12","restSec":120,"sets":3,"wk1Kg":32},{"compound":true,"cutSets":3,"exerciseId":"2eaa26ca-61d7-462c-92f4-45781c5869b4","name":"Lat Pulldown","reps":"8–12","restSec":135,"sets":3,"wk1Kg":45},{"compound":true,"cutSets":2,"exerciseId":"81657991-ecd7-474b-a9c9-ccd2d7df4157","name":"Chest Press","reps":"10–12","restSec":135,"sets":3,"wk1Kg":34},{"compound":true,"cutSets":2,"exerciseId":"8bd1aada-fa77-464e-960b-784647a95fcf","name":"Seated Cable Row (V-Grip)","note":"V-grip","reps":"10–12","restSec":120,"sets":3,"wk1Kg":38.5},{"compound":false,"cutSets":2,"exerciseId":"33456a42-aa5b-43d9-87f7-f27c09298c40","name":"Pec Deck","reps":"12–15","restSec":120,"sets":2,"wk1Kg":47.5},{"compound":false,"cutSets":3,"exerciseId":"04fdd423-cb00-46bb-a711-5c30a5dbec0e","name":"Straight-Arm Pulldown","reps":"12–15","restSec":105,"sets":3,"wk1Kg":15},{"compound":false,"cutSets":3,"exerciseId":"3a3acfe4-4ffd-4bee-9884-f6b7b09223fa","name":"Face Pull","reps":"12–15","restSec":105,"sets":3,"wk1Kg":13.75}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'legs_a', 'Legs & Core A', 'Quad Focus', 1, 4029112, 1,
        '{"exercises":[{"compound":true,"cutSets":3,"exerciseId":"918e8f8d-10b4-4609-9c86-b4df8ffba523","name":"Leg Press","note":"1 warm-up @40kg","reps":"8–12","restSec":135,"sets":4,"wk1Kg":70},{"compound":true,"cutSets":2,"exerciseId":"07e99254-df7f-463e-b9b2-bd11a0dd022a","name":"Hack Squat","reps":"10–12","restSec":135,"sets":3},{"compound":false,"cutSets":3,"exerciseId":"447184a0-e31e-4946-9791-826c32d57eef","name":"Leg Extension","reps":"12–15","restSec":120,"sets":3,"wk1Kg":37.5},{"compound":false,"cutSets":3,"exerciseId":"be4ce30b-d143-487a-924e-3c25bc22154d","name":"Seated Leg Curl","reps":"10–15","restSec":105,"sets":3,"wk1Kg":40},{"compound":false,"cutSets":3,"exerciseId":"66037198-a6b0-4af5-a7af-706c37e666cd","name":"Calf Press","reps":"10–15","restSec":90,"sets":4,"wk1Kg":65},{"compound":false,"cutSets":3,"exerciseId":"8ee210f3-1cb2-4bba-9c08-e1305535cbc0","name":"Crunch Machine","reps":"10–12","restSec":90,"sets":3,"wk1Kg":52.5},{"compound":false,"cutSets":3,"exerciseId":"b0763b58-4555-425d-802f-e7e6850194e4","name":"Reverse Crunch","reps":"12–15","restSec":75,"sets":3}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'arms', 'Delts & Arms', null, 2, 9072552, 2,
        '{"exercises":[{"compound":true,"cutSets":3,"exerciseId":"40ce6b78-4e9b-4e2c-b5f0-5fdc2e9f1083","name":"Shoulder Press","reps":"8–10","restSec":105,"sets":3,"wk1Kg":28},{"compound":false,"cutSets":4,"exerciseId":"c528edde-6a93-4e8a-a20a-325837d36174","name":"Single Arm Lateral Raise","note":"per side","reps":"12–20","restSec":105,"sets":5,"wk1Kg":5},{"compound":false,"cutSets":3,"exerciseId":"227afcfc-3c38-4104-b5ca-1717a8f2e67e","name":"Seated Incline DB Curl","reps":"8–12","restSec":105,"sets":3,"wk1Kg":14},{"compound":false,"cutSets":3,"exerciseId":"c2bf052f-4128-40c0-a0db-d2d48df41f84","name":"Overhead Triceps Extension","reps":"10–15","restSec":90,"sets":3,"wk1Kg":9},{"compound":false,"cutSets":3,"exerciseId":"e0031f39-97eb-4e5e-8672-7eb00d362c7e","name":"Hammer Curl","reps":"10–12","restSec":105,"sets":3,"wk1Kg":16},{"compound":false,"cutSets":2,"exerciseId":"de056933-d71e-44ee-97d6-65954dbf82a2","name":"Rope Triceps Pushdown","reps":"12–15","restSec":90,"sets":2,"wk1Kg":13.5},{"compound":false,"cutSets":2,"exerciseId":"5631ea58-b9e9-4b7e-93be-b89044d4ef97","name":"Reverse EZ-Bar Curl","reps":"12–15","restSec":90,"sets":2,"wk1Kg":15},{"compound":false,"cutSets":0,"exerciseId":"8cbc3b90-20e6-4b99-8124-1e0a01920ad3","name":"Seated DB Wrist Curl","reps":"15–20","restSec":90,"sets":2,"wk1Kg":16}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cb_b', 'Upper B', 'Chest + Back', 4, 11817514, 3,
        '{"exercises":[{"compound":true,"cutSets":3,"exerciseId":"81657991-ecd7-474b-a9c9-ccd2d7df4157","name":"Chest Press","reps":"10–12","restSec":120,"sets":3,"wk1Kg":35},{"compound":true,"cutSets":2,"exerciseId":"44ef3d06-c0c2-47b3-bedc-6860085b6622","name":"Neutral-Grip Lat Pulldown","reps":"10–12","restSec":120,"sets":3,"wk1Kg":45},{"compound":false,"cutSets":2,"exerciseId":"a213f4e3-093d-45d3-bdd4-959ee7a0db7b","name":"Single Arm Cable Crossover","note":"per arm","reps":"12–15","restSec":105,"sets":2,"wk1Kg":7.5},{"compound":true,"cutSets":2,"exerciseId":"2c397ee9-57af-4f84-9790-8552ecbda124","name":"Seated Cable Row (Wide Grip)","note":"wide bar","reps":"10–12","restSec":120,"sets":3,"wk1Kg":35},{"compound":false,"cutSets":3,"exerciseId":"c528edde-6a93-4e8a-a20a-325837d36174","name":"Single Arm Lateral Raise","note":"per side","reps":"15–20","restSec":90,"sets":4,"wk1Kg":3.75},{"compound":false,"cutSets":3,"exerciseId":"57c6bd41-0456-4bb1-8d6b-7f6ff482089b","name":"Preacher Curl","reps":"8–12","restSec":105,"sets":3,"wk1Kg":15},{"compound":false,"cutSets":3,"exerciseId":"22b483f9-1a57-4adb-99db-4e4504826ea6","name":"Single Arm Triceps Pushdown","note":"per arm","reps":"12–15","restSec":90,"sets":3,"wk1Kg":5}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'legs_b', 'Legs & Core B', 'Posterior Focus', 5, 3038346, 4,
        '{"exercises":[{"compound":true,"cutSets":3,"exerciseId":"ba5f3ca2-450c-4f92-a5fd-6870a36faf83","name":"Romanian Deadlift","reps":"8–12","restSec":120,"sets":4,"wk1Kg":30},{"compound":true,"cutSets":3,"exerciseId":"2bdee111-02a7-4abc-9b58-877dabadd57c","name":"Hip Thrust","reps":"8–15","restSec":135,"sets":3,"wk1Kg":25},{"compound":true,"cutSets":2,"exerciseId":"918e8f8d-10b4-4609-9c86-b4df8ffba523","name":"Leg Press","note":"horizontal sled","reps":"12–15","restSec":135,"sets":2,"wk1Kg":70},{"compound":false,"cutSets":0,"exerciseId":"c70b57b0-ab44-4a0f-bd58-6f2db8c37898","name":"Hip Adduction","reps":"12–15","restSec":90,"sets":2,"wk1Kg":50},{"compound":false,"cutSets":2,"exerciseId":"be4ce30b-d143-487a-924e-3c25bc22154d","name":"Seated Leg Curl","reps":"10–15","restSec":105,"sets":2,"wk1Kg":45},{"compound":false,"cutSets":3,"exerciseId":"66037198-a6b0-4af5-a7af-706c37e666cd","name":"Calf Press","reps":"10–15","restSec":105,"sets":4,"wk1Kg":67.5},{"compound":false,"cutSets":3,"exerciseId":"c6627399-f44e-4abb-97b8-ca0c36881843","name":"Hanging Knee Raise","reps":"10–15","restSec":90,"sets":3},{"compound":false,"cutSets":2,"exerciseId":"57b224bc-fe35-41b1-b0a9-545734667084","name":"Side Plank","note":"per side","reps":"55s","restSec":90,"sets":2}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'upper_a', 'Upper A', null, 1, 14708796, 0,
        '{"exercises":[{"compound":true,"cutSets":3,"exerciseId":"d1bb00f2-f88d-4a6c-80b1-e6cd6f9136a2","name":"Incline DB Press","reps":"8–12","restSec":120,"sets":3,"wk1Kg":32},{"compound":true,"cutSets":3,"exerciseId":"2eaa26ca-61d7-462c-92f4-45781c5869b4","name":"Lat Pulldown","reps":"8–12","restSec":135,"sets":3,"wk1Kg":45},{"compound":true,"cutSets":0,"exerciseId":"81657991-ecd7-474b-a9c9-ccd2d7df4157","name":"Chest Press","reps":"10–12","restSec":120,"sets":2,"wk1Kg":34},{"compound":true,"cutSets":2,"exerciseId":"8bd1aada-fa77-464e-960b-784647a95fcf","name":"Seated Cable Row (V-Grip)","note":"V-grip","reps":"10–12","restSec":120,"sets":3,"wk1Kg":38.5},{"compound":false,"cutSets":3,"exerciseId":"227afcfc-3c38-4104-b5ca-1717a8f2e67e","name":"Seated Incline DB Curl","reps":"8–12","restSec":105,"sets":3,"wk1Kg":14},{"compound":false,"cutSets":2,"exerciseId":"de056933-d71e-44ee-97d6-65954dbf82a2","name":"Rope Triceps Pushdown","reps":"12–15","restSec":90,"sets":3,"wk1Kg":13.5},{"compound":false,"cutSets":2,"exerciseId":"3a3acfe4-4ffd-4bee-9884-f6b7b09223fa","name":"Face Pull","reps":"12–15","restSec":105,"sets":2,"wk1Kg":13.75}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'lower_a', 'Lower A', null, 2, 4029112, 1,
        '{"exercises":[{"compound":true,"cutSets":3,"exerciseId":"918e8f8d-10b4-4609-9c86-b4df8ffba523","name":"Leg Press","reps":"8–12","restSec":135,"sets":3,"wk1Kg":70},{"compound":true,"cutSets":0,"exerciseId":"07e99254-df7f-463e-b9b2-bd11a0dd022a","name":"Hack Squat","reps":"10–12","restSec":135,"sets":2},{"compound":false,"cutSets":3,"exerciseId":"447184a0-e31e-4946-9791-826c32d57eef","name":"Leg Extension","reps":"12–15","restSec":120,"sets":2,"wk1Kg":37.5},{"compound":false,"cutSets":3,"exerciseId":"be4ce30b-d143-487a-924e-3c25bc22154d","name":"Seated Leg Curl","reps":"10–15","restSec":105,"sets":3,"wk1Kg":40},{"compound":false,"cutSets":3,"exerciseId":"66037198-a6b0-4af5-a7af-706c37e666cd","name":"Calf Press","reps":"10–15","restSec":90,"sets":4,"wk1Kg":65},{"compound":false,"cutSets":3,"exerciseId":"8ee210f3-1cb2-4bba-9c08-e1305535cbc0","name":"Crunch Machine","reps":"10–12","restSec":90,"sets":3,"wk1Kg":52.5},{"compound":false,"cutSets":2,"exerciseId":"b0763b58-4555-425d-802f-e7e6850194e4","name":"Reverse Crunch","reps":"12–15","restSec":75,"sets":2}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'upper_b', 'Upper B', null, 4, 11817514, 2,
        '{"exercises":[{"compound":true,"cutSets":3,"exerciseId":"40ce6b78-4e9b-4e2c-b5f0-5fdc2e9f1083","name":"Shoulder Press","reps":"8–10","restSec":105,"sets":3,"wk1Kg":28},{"compound":false,"cutSets":4,"exerciseId":"c528edde-6a93-4e8a-a20a-325837d36174","name":"Single Arm Lateral Raise","note":"per side","reps":"12–20","restSec":105,"sets":4,"wk1Kg":5},{"compound":false,"cutSets":1,"exerciseId":"33456a42-aa5b-43d9-87f7-f27c09298c40","name":"Pec Deck","note":"cut: rotates with Chest Press (Machine)","reps":"12–15","restSec":120,"sets":2,"wk1Kg":47.5},{"compound":true,"cutSets":2,"exerciseId":"2c397ee9-57af-4f84-9790-8552ecbda124","name":"Seated Cable Row (Wide Grip)","note":"wide bar","reps":"10–12","restSec":120,"sets":3,"wk1Kg":35},{"compound":false,"cutSets":2,"exerciseId":"e0031f39-97eb-4e5e-8672-7eb00d362c7e","name":"Hammer Curl","reps":"10–12","restSec":105,"sets":3,"wk1Kg":16},{"compound":false,"cutSets":2,"exerciseId":"22b483f9-1a57-4adb-99db-4e4504826ea6","name":"Single Arm Triceps Pushdown","note":"per arm","reps":"12–15","restSec":90,"sets":2,"wk1Kg":5},{"compound":false,"cutSets":2,"exerciseId":"5631ea58-b9e9-4b7e-93be-b89044d4ef97","name":"Reverse EZ-Bar Curl","reps":"12–15","restSec":90,"sets":2,"wk1Kg":15},{"compound":false,"cutSets":0,"exerciseId":"8cbc3b90-20e6-4b99-8124-1e0a01920ad3","name":"Seated DB Wrist Curl","reps":"15–20","restSec":90,"sets":2,"wk1Kg":16}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'lower_b', 'Lower B', null, 5, 3038346, 3,
        '{"exercises":[{"compound":true,"cutSets":3,"exerciseId":"ba5f3ca2-450c-4f92-a5fd-6870a36faf83","name":"Romanian Deadlift","reps":"8–12","restSec":120,"sets":3,"wk1Kg":26},{"compound":true,"cutSets":3,"exerciseId":"2bdee111-02a7-4abc-9b58-877dabadd57c","name":"Hip Thrust","reps":"8–15","restSec":135,"sets":3,"wk1Kg":23.5},{"compound":true,"cutSets":2,"exerciseId":"918e8f8d-10b4-4609-9c86-b4df8ffba523","name":"Leg Press","note":"horizontal sled","reps":"12–15","restSec":135,"sets":2,"wk1Kg":70},{"compound":false,"cutSets":0,"exerciseId":"c70b57b0-ab44-4a0f-bd58-6f2db8c37898","name":"Hip Adduction","reps":"12–15","restSec":90,"sets":2,"wk1Kg":50},{"compound":false,"cutSets":3,"exerciseId":"66037198-a6b0-4af5-a7af-706c37e666cd","name":"Calf Press","reps":"10–15","restSec":105,"sets":3,"wk1Kg":65},{"compound":false,"cutSets":3,"exerciseId":"c6627399-f44e-4abb-97b8-ca0c36881843","name":"Hanging Knee Raise","reps":"10–15","restSec":90,"sets":3},{"compound":false,"cutSets":2,"exerciseId":"57b224bc-fe35-41b1-b0a9-545734667084","name":"Side Plank","note":"per side","reps":"55s","restSec":90,"sets":2}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'ppl_push_sun', 'Push', null, 0, 14708796, 0,
        '{"exercises":[{"compound":true,"exerciseId":"d1bb00f2-f88d-4a6c-80b1-e6cd6f9136a2","name":"Incline DB Press","reps":"10–12","sets":2,"wk1Kg":35},{"compound":true,"name":"Chest Press Machine","reps":"10–12","sets":2,"wk1Kg":37.5},{"compound":false,"name":"Butterfly Pec Deck","reps":"10–12","sets":2,"wk1Kg":52.5},{"compound":true,"exerciseId":"40ce6b78-4e9b-4e2c-b5f0-5fdc2e9f1083","name":"Shoulder Press","note":"ramp: 25kg×12 → 30kg×9,8","reps":"8–12","sets":3,"wk1Kg":30},{"compound":false,"name":"Lateral Raise DB","reps":"12–20","sets":4,"wk1Kg":10},{"compound":false,"exerciseId":"de056933-d71e-44ee-97d6-65954dbf82a2","name":"Rope Triceps Pushdown","reps":"12–15","sets":3,"wk1Kg":15},{"compound":false,"exerciseId":"c2bf052f-4128-40c0-a0db-d2d48df41f84","name":"Overhead Triceps Extension","reps":"10–15","sets":3,"wk1Kg":10},{"compound":false,"exerciseId":"57b224bc-fe35-41b1-b0a9-545734667084","name":"Side Plank","note":"per side","reps":"55s","sets":3},{"compound":false,"exerciseId":"da0a4251-4603-4987-969e-33b47b399d09","name":"Russian Twist","reps":"15–20","sets":3,"wk1Kg":10},{"compound":false,"name":"Lying Leg Raises","reps":"12–15","sets":3}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'ppl_pull_mon', 'Pull', null, 1, 4103802, 1,
        '{"exercises":[{"compound":true,"exerciseId":"2eaa26ca-61d7-462c-92f4-45781c5869b4","name":"Lat Pulldown","reps":"10–12","sets":2,"wk1Kg":49.5},{"compound":true,"exerciseId":"71bd5b9d-a91c-43a1-876b-a8644e8a842f","name":"Seated Cable Row","reps":"10–12","sets":2,"wk1Kg":42.5},{"compound":false,"exerciseId":"3a3acfe4-4ffd-4bee-9884-f6b7b09223fa","name":"Face Pull","reps":"12–15","sets":4,"wk1Kg":16.25},{"compound":false,"exerciseId":"04fdd423-cb00-46bb-a711-5c30a5dbec0e","name":"Straight Arm Pulldown","reps":"10–15","sets":3,"wk1Kg":17.5},{"compound":false,"name":"Bicep Curl DB","reps":"10–12","sets":3,"wk1Kg":18},{"compound":false,"name":"Hammer Curl DB","reps":"10–12","sets":3,"wk1Kg":18},{"compound":false,"exerciseId":"57c6bd41-0456-4bb1-8d6b-7f6ff482089b","name":"Preacher Curl","reps":"8–12","sets":3,"wk1Kg":16.25},{"compound":false,"exerciseId":"8ee210f3-1cb2-4bba-9c08-e1305535cbc0","name":"Crunch Machine","reps":"12–15","sets":3,"wk1Kg":57.5}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'ppl_legs_tue', 'Legs', null, 2, 4029112, 2,
        '{"exercises":[{"compound":true,"exerciseId":"918e8f8d-10b4-4609-9c86-b4df8ffba523","name":"Leg Press","note":"1 warm-up @72.5kg","reps":"8–12","sets":2,"wk1Kg":80},{"compound":true,"name":"RDL DB","reps":"10–15","sets":3,"wk1Kg":30},{"compound":true,"exerciseId":"2bdee111-02a7-4abc-9b58-877dabadd57c","name":"Hip Thrust","reps":"10–15","sets":3,"wk1Kg":27.5},{"compound":false,"exerciseId":"c70b57b0-ab44-4a0f-bd58-6f2db8c37898","name":"Hip Adduction","reps":"12–15","sets":3,"wk1Kg":55},{"compound":false,"exerciseId":"447184a0-e31e-4946-9791-826c32d57eef","name":"Leg Extension","reps":"10–15","sets":3,"wk1Kg":42.5},{"compound":false,"exerciseId":"be4ce30b-d143-487a-924e-3c25bc22154d","name":"Seated Leg Curl","reps":"10–15","sets":2,"wk1Kg":45},{"compound":false,"exerciseId":"66037198-a6b0-4af5-a7af-706c37e666cd","name":"Calf Press","reps":"10–15","sets":3,"wk1Kg":72.5},{"compound":false,"exerciseId":"b0763b58-4555-425d-802f-e7e6850194e4","name":"Reverse Crunch","reps":"15–20","sets":3},{"compound":false,"exerciseId":"335e4d62-7b82-4c9b-b78d-78cd1e7241fc","name":"Hollow Rock","note":"seconds","reps":"38s","sets":3}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'ppl_push_thu', 'Push', null, 4, 14708796, 3,
        '{"exercises":[{"compound":true,"exerciseId":"d1bb00f2-f88d-4a6c-80b1-e6cd6f9136a2","name":"Incline DB Press","reps":"10–12","sets":2,"wk1Kg":35},{"compound":true,"name":"Chest Press Machine","reps":"10–12","sets":2,"wk1Kg":37.5},{"compound":false,"name":"Butterfly Pec Deck","reps":"10–12","sets":2,"wk1Kg":52.5},{"compound":true,"exerciseId":"40ce6b78-4e9b-4e2c-b5f0-5fdc2e9f1083","name":"Shoulder Press","note":"ramp: 25kg×12 → 30kg×9,8","reps":"8–12","sets":3,"wk1Kg":30},{"compound":false,"name":"Lateral Raise DB","reps":"12–20","sets":4,"wk1Kg":10},{"compound":false,"exerciseId":"de056933-d71e-44ee-97d6-65954dbf82a2","name":"Rope Triceps Pushdown","reps":"12–15","sets":3,"wk1Kg":15},{"compound":false,"exerciseId":"c2bf052f-4128-40c0-a0db-d2d48df41f84","name":"Overhead Triceps Extension","reps":"10–15","sets":3,"wk1Kg":10},{"compound":false,"exerciseId":"57b224bc-fe35-41b1-b0a9-545734667084","name":"Side Plank","note":"per side","reps":"55s","sets":3},{"compound":false,"exerciseId":"da0a4251-4603-4987-969e-33b47b399d09","name":"Russian Twist","reps":"15–20","sets":3,"wk1Kg":10},{"compound":false,"name":"Lying Leg Raises","reps":"12–15","sets":3}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;
insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'ppl_pull_fri', 'Pull', null, 5, 4103802, 4,
        '{"exercises":[{"compound":true,"exerciseId":"2eaa26ca-61d7-462c-92f4-45781c5869b4","name":"Lat Pulldown","reps":"10–12","sets":2,"wk1Kg":49.5},{"compound":true,"exerciseId":"71bd5b9d-a91c-43a1-876b-a8644e8a842f","name":"Seated Cable Row","reps":"10–12","sets":2,"wk1Kg":42.5},{"compound":false,"exerciseId":"3a3acfe4-4ffd-4bee-9884-f6b7b09223fa","name":"Face Pull","reps":"12–15","sets":4,"wk1Kg":16.25},{"compound":false,"exerciseId":"04fdd423-cb00-46bb-a711-5c30a5dbec0e","name":"Straight Arm Pulldown","reps":"10–15","sets":3,"wk1Kg":17.5},{"compound":false,"name":"Bicep Curl DB","reps":"10–12","sets":3,"wk1Kg":18},{"compound":false,"name":"Hammer Curl DB","reps":"10–12","sets":3,"wk1Kg":18},{"compound":false,"exerciseId":"57c6bd41-0456-4bb1-8d6b-7f6ff482089b","name":"Preacher Curl","reps":"8–12","sets":3,"wk1Kg":16.25},{"compound":false,"exerciseId":"8ee210f3-1cb2-4bba-9c08-e1305535cbc0","name":"Crunch Machine","reps":"12–15","sets":3,"wk1Kg":57.5}],"version":1}'::jsonb)
on conflict (user_id, program_id, day_key) do nothing;

-- ── 3 · plan_phases — the eight dated blocks ───────────────────────────────
insert into public.plan_phases (user_id, plan_id, start, kind, name, short, weeks, numbered, first_week, era, era_tag)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', '2026-03-08', 'bulk', 'Bulk', null, 9, true, null, 'ppl', 'PPL Bulk')
on conflict (user_id, plan_id, start) do nothing;
insert into public.plan_phases (user_id, plan_id, start, kind, name, short, weeks, numbered, first_week, era, era_tag)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', '2026-05-10', 'cut', 'Cut', null, 6, true, null, 'ppl', 'PPL Cut')
on conflict (user_id, plan_id, start) do nothing;
insert into public.plan_phases (user_id, plan_id, start, kind, name, short, weeks, numbered, first_week, era, era_tag)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', '2026-06-21', 'peak', 'Peak Week (Maintenance)', 'Peak', 1, false, null, 'ppl', 'PPL Peak')
on conflict (user_id, plan_id, start) do nothing;
insert into public.plan_phases (user_id, plan_id, start, kind, name, short, weeks, numbered, first_week, era, era_tag)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', '2026-06-28', 'deload', 'Thailand Vacation', 'Thailand', 2, false, null, 'ppl', 'Thailand Vacation (Deload)')
on conflict (user_id, plan_id, start) do nothing;
insert into public.plan_phases (user_id, plan_id, start, kind, name, short, weeks, numbered, first_week, era, era_tag)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', '2026-07-12', 'peak', 'Week 0 · Transition', 'W0', 1, false, null, 'helix', 'Onyx · Week 0')
on conflict (user_id, plan_id, start) do nothing;
insert into public.plan_phases (user_id, plan_id, start, kind, name, short, weeks, numbered, first_week, era, era_tag)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', '2026-07-19', 'cut', 'Cut', null, 13, true, null, 'helix', 'Onyx Cut')
on conflict (user_id, plan_id, start) do nothing;
insert into public.plan_phases (user_id, plan_id, start, kind, name, short, weeks, numbered, first_week, era, era_tag)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', '2026-10-18', 'deload', 'Transition', 'Trans', 2, true, null, 'helix', 'Onyx Transition')
on conflict (user_id, plan_id, start) do nothing;
insert into public.plan_phases (user_id, plan_id, start, kind, name, short, weeks, numbered, first_week, era, era_tag)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', '2026-11-01', 'bulk', 'Lean Bulk', null, 11, true, null, 'helix', 'Onyx Lean Bulk')
on conflict (user_id, plan_id, start) do nothing;

-- ── 4 · target_profiles — the ladder's rungs, as profiles with a kind ──────
insert into public.target_profiles (user_id, key, label, summary, sort, kcal, protein_g, carbs_g, fat_g, steps_goal, kind)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'baseline', 'Baseline', 'The plan as written — 190 g carbs, 10k steps.', 10, 1935, 170, 190, 55, 10000, 'deficit')
on conflict (user_id, key) do update set kind = excluded.kind;
insert into public.target_profiles (user_id, key, label, summary, sort, kcal, protein_g, carbs_g, fat_g, steps_goal, kind)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'lever-1', 'Lever 1', '−70 kcal off carbs and fat, steps to 10k.', 11, 1885, 170, 182, 53, 10000, 'deficit')
on conflict (user_id, key) do update set kind = excluded.kind;
insert into public.target_profiles (user_id, key, label, summary, sort, kcal, protein_g, carbs_g, fat_g, steps_goal, kind)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'lever-2', 'Lever 2', 'Same food as Lever 1, steps 12k–15k. The last rung.', 12, 1885, 170, 182, 53, 12000, 'deficit')
on conflict (user_id, key) do update set kind = excluded.kind;
insert into public.target_profiles (user_id, key, label, summary, sort, kcal, protein_g, carbs_g, fat_g, steps_goal, kind)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'maintenance-week', 'Maintenance Week', 'A planned week at maintenance — full food, lighter steps. Still cutting.', 13, 2151, 170, 244, 55, 7500, 'release')
on conflict (user_id, key) do update set kind = excluded.kind;

-- ── 5 · lever_periods — when each rung came into force ─────────────────────
insert into public.lever_periods (user_id, starts_on, profile_key, goals)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, '2026-07-15', 'baseline', null)
on conflict (user_id, starts_on) do nothing;
insert into public.lever_periods (user_id, starts_on, profile_key, goals)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, '2026-08-16', 'lever-1', null)
on conflict (user_id, starts_on) do nothing;
insert into public.lever_periods (user_id, starts_on, profile_key, goals)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, '2026-08-20', null, '{"calorie":1999,"carbs":206,"fat":55,"protein":170,"steps":10000}'::jsonb)
on conflict (user_id, starts_on) do nothing;
insert into public.lever_periods (user_id, starts_on, profile_key, goals)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, '2026-08-30', 'maintenance-week', null)
on conflict (user_id, starts_on) do nothing;
insert into public.lever_periods (user_id, starts_on, profile_key, goals)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, '2026-09-06', 'baseline', null)
on conflict (user_id, starts_on) do nothing;

-- ── 6 · plan_phase_goals — merged: a NULL column takes the constant, an edit stays ──
insert into public.plan_phase_goals (user_id, plan_id, phase, label, kcal, protein_g, carbs_g, fat_g, fiber_g, fiber_min, fiber_max, steps_goal,
                                     target_weight_kg, target_body_fat_pct, target_muscle_mass_kg, rate_min_kg_wk, rate_max_kg_wk, body_fat_ceiling_pct)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Cut', 1955, 170, 195, 55, 30, 28, 35, 10000,
        62, 13, 33, -0.5, -0.4, null)
on conflict (user_id, plan_id, phase) do update set
  label = coalesce(plan_phase_goals.label, excluded.label),
  kcal = coalesce(plan_phase_goals.kcal, excluded.kcal),
  protein_g = coalesce(plan_phase_goals.protein_g, excluded.protein_g),
  carbs_g = coalesce(plan_phase_goals.carbs_g, excluded.carbs_g),
  fat_g = coalesce(plan_phase_goals.fat_g, excluded.fat_g),
  fiber_g = coalesce(plan_phase_goals.fiber_g, excluded.fiber_g),
  fiber_min = coalesce(plan_phase_goals.fiber_min, excluded.fiber_min),
  fiber_max = coalesce(plan_phase_goals.fiber_max, excluded.fiber_max),
  steps_goal = coalesce(plan_phase_goals.steps_goal, excluded.steps_goal),
  target_weight_kg = coalesce(plan_phase_goals.target_weight_kg, excluded.target_weight_kg),
  target_body_fat_pct = coalesce(plan_phase_goals.target_body_fat_pct, excluded.target_body_fat_pct),
  target_muscle_mass_kg = coalesce(plan_phase_goals.target_muscle_mass_kg, excluded.target_muscle_mass_kg),
  rate_min_kg_wk = coalesce(plan_phase_goals.rate_min_kg_wk, excluded.rate_min_kg_wk),
  rate_max_kg_wk = coalesce(plan_phase_goals.rate_max_kg_wk, excluded.rate_max_kg_wk),
  body_fat_ceiling_pct = coalesce(plan_phase_goals.body_fat_ceiling_pct, excluded.body_fat_ceiling_pct);
insert into public.plan_phase_goals (user_id, plan_id, phase, label, kcal, protein_g, carbs_g, fat_g, fiber_g, fiber_min, fiber_max, steps_goal,
                                     target_weight_kg, target_body_fat_pct, target_muscle_mass_kg, rate_min_kg_wk, rate_max_kg_wk, body_fat_ceiling_pct)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Lean Bulk', 2600, 160, 330, 70, 35, 33, 38, 8000,
        70, 15, 37, 0.2, 0.25, 16)
on conflict (user_id, plan_id, phase) do update set
  label = coalesce(plan_phase_goals.label, excluded.label),
  kcal = coalesce(plan_phase_goals.kcal, excluded.kcal),
  protein_g = coalesce(plan_phase_goals.protein_g, excluded.protein_g),
  carbs_g = coalesce(plan_phase_goals.carbs_g, excluded.carbs_g),
  fat_g = coalesce(plan_phase_goals.fat_g, excluded.fat_g),
  fiber_g = coalesce(plan_phase_goals.fiber_g, excluded.fiber_g),
  fiber_min = coalesce(plan_phase_goals.fiber_min, excluded.fiber_min),
  fiber_max = coalesce(plan_phase_goals.fiber_max, excluded.fiber_max),
  steps_goal = coalesce(plan_phase_goals.steps_goal, excluded.steps_goal),
  target_weight_kg = coalesce(plan_phase_goals.target_weight_kg, excluded.target_weight_kg),
  target_body_fat_pct = coalesce(plan_phase_goals.target_body_fat_pct, excluded.target_body_fat_pct),
  target_muscle_mass_kg = coalesce(plan_phase_goals.target_muscle_mass_kg, excluded.target_muscle_mass_kg),
  rate_min_kg_wk = coalesce(plan_phase_goals.rate_min_kg_wk, excluded.rate_min_kg_wk),
  rate_max_kg_wk = coalesce(plan_phase_goals.rate_max_kg_wk, excluded.rate_max_kg_wk),
  body_fat_ceiling_pct = coalesce(plan_phase_goals.body_fat_ceiling_pct, excluded.body_fat_ceiling_pct);
insert into public.plan_phase_goals (user_id, plan_id, phase, label, kcal, protein_g, carbs_g, fat_g, fiber_g, fiber_min, fiber_max, steps_goal,
                                     target_weight_kg, target_body_fat_pct, target_muscle_mass_kg, rate_min_kg_wk, rate_max_kg_wk, body_fat_ceiling_pct)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Cut', 1955, 170, 195, 55, 30, 28, 35, 10000,
        62, 13, 33, -0.5, -0.4, null)
on conflict (user_id, plan_id, phase) do update set
  label = coalesce(plan_phase_goals.label, excluded.label),
  kcal = coalesce(plan_phase_goals.kcal, excluded.kcal),
  protein_g = coalesce(plan_phase_goals.protein_g, excluded.protein_g),
  carbs_g = coalesce(plan_phase_goals.carbs_g, excluded.carbs_g),
  fat_g = coalesce(plan_phase_goals.fat_g, excluded.fat_g),
  fiber_g = coalesce(plan_phase_goals.fiber_g, excluded.fiber_g),
  fiber_min = coalesce(plan_phase_goals.fiber_min, excluded.fiber_min),
  fiber_max = coalesce(plan_phase_goals.fiber_max, excluded.fiber_max),
  steps_goal = coalesce(plan_phase_goals.steps_goal, excluded.steps_goal),
  target_weight_kg = coalesce(plan_phase_goals.target_weight_kg, excluded.target_weight_kg),
  target_body_fat_pct = coalesce(plan_phase_goals.target_body_fat_pct, excluded.target_body_fat_pct),
  target_muscle_mass_kg = coalesce(plan_phase_goals.target_muscle_mass_kg, excluded.target_muscle_mass_kg),
  rate_min_kg_wk = coalesce(plan_phase_goals.rate_min_kg_wk, excluded.rate_min_kg_wk),
  rate_max_kg_wk = coalesce(plan_phase_goals.rate_max_kg_wk, excluded.rate_max_kg_wk),
  body_fat_ceiling_pct = coalesce(plan_phase_goals.body_fat_ceiling_pct, excluded.body_fat_ceiling_pct);
insert into public.plan_phase_goals (user_id, plan_id, phase, label, kcal, protein_g, carbs_g, fat_g, fiber_g, fiber_min, fiber_max, steps_goal,
                                     target_weight_kg, target_body_fat_pct, target_muscle_mass_kg, rate_min_kg_wk, rate_max_kg_wk, body_fat_ceiling_pct)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Lean Bulk', 2600, 160, 330, 70, 35, 33, 38, 8000,
        70, 15, 37, 0.2, 0.25, 16)
on conflict (user_id, plan_id, phase) do update set
  label = coalesce(plan_phase_goals.label, excluded.label),
  kcal = coalesce(plan_phase_goals.kcal, excluded.kcal),
  protein_g = coalesce(plan_phase_goals.protein_g, excluded.protein_g),
  carbs_g = coalesce(plan_phase_goals.carbs_g, excluded.carbs_g),
  fat_g = coalesce(plan_phase_goals.fat_g, excluded.fat_g),
  fiber_g = coalesce(plan_phase_goals.fiber_g, excluded.fiber_g),
  fiber_min = coalesce(plan_phase_goals.fiber_min, excluded.fiber_min),
  fiber_max = coalesce(plan_phase_goals.fiber_max, excluded.fiber_max),
  steps_goal = coalesce(plan_phase_goals.steps_goal, excluded.steps_goal),
  target_weight_kg = coalesce(plan_phase_goals.target_weight_kg, excluded.target_weight_kg),
  target_body_fat_pct = coalesce(plan_phase_goals.target_body_fat_pct, excluded.target_body_fat_pct),
  target_muscle_mass_kg = coalesce(plan_phase_goals.target_muscle_mass_kg, excluded.target_muscle_mass_kg),
  rate_min_kg_wk = coalesce(plan_phase_goals.rate_min_kg_wk, excluded.rate_min_kg_wk),
  rate_max_kg_wk = coalesce(plan_phase_goals.rate_max_kg_wk, excluded.rate_max_kg_wk),
  body_fat_ceiling_pct = coalesce(plan_phase_goals.body_fat_ceiling_pct, excluded.body_fat_ceiling_pct);
insert into public.plan_phase_goals (user_id, plan_id, phase, label, kcal, protein_g, carbs_g, fat_g, fiber_g, fiber_min, fiber_max, steps_goal,
                                     target_weight_kg, target_body_fat_pct, target_muscle_mass_kg, rate_min_kg_wk, rate_max_kg_wk, body_fat_ceiling_pct)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'PPL Cut', 1935, 180, 180, 55, 30, 28, 35, 10000,
        62, 13, 33, -0.5, -0.4, null)
on conflict (user_id, plan_id, phase) do update set
  label = coalesce(plan_phase_goals.label, excluded.label),
  kcal = coalesce(plan_phase_goals.kcal, excluded.kcal),
  protein_g = coalesce(plan_phase_goals.protein_g, excluded.protein_g),
  carbs_g = coalesce(plan_phase_goals.carbs_g, excluded.carbs_g),
  fat_g = coalesce(plan_phase_goals.fat_g, excluded.fat_g),
  fiber_g = coalesce(plan_phase_goals.fiber_g, excluded.fiber_g),
  fiber_min = coalesce(plan_phase_goals.fiber_min, excluded.fiber_min),
  fiber_max = coalesce(plan_phase_goals.fiber_max, excluded.fiber_max),
  steps_goal = coalesce(plan_phase_goals.steps_goal, excluded.steps_goal),
  target_weight_kg = coalesce(plan_phase_goals.target_weight_kg, excluded.target_weight_kg),
  target_body_fat_pct = coalesce(plan_phase_goals.target_body_fat_pct, excluded.target_body_fat_pct),
  target_muscle_mass_kg = coalesce(plan_phase_goals.target_muscle_mass_kg, excluded.target_muscle_mass_kg),
  rate_min_kg_wk = coalesce(plan_phase_goals.rate_min_kg_wk, excluded.rate_min_kg_wk),
  rate_max_kg_wk = coalesce(plan_phase_goals.rate_max_kg_wk, excluded.rate_max_kg_wk),
  body_fat_ceiling_pct = coalesce(plan_phase_goals.body_fat_ceiling_pct, excluded.body_fat_ceiling_pct);
insert into public.plan_phase_goals (user_id, plan_id, phase, label, kcal, protein_g, carbs_g, fat_g, fiber_g, fiber_min, fiber_max, steps_goal,
                                     target_weight_kg, target_body_fat_pct, target_muscle_mass_kg, rate_min_kg_wk, rate_max_kg_wk, body_fat_ceiling_pct)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Lean Bulk', 2600, 160, 330, 70, 35, 33, 38, 8000,
        70, 15, 37, 0.2, 0.25, 16)
on conflict (user_id, plan_id, phase) do update set
  label = coalesce(plan_phase_goals.label, excluded.label),
  kcal = coalesce(plan_phase_goals.kcal, excluded.kcal),
  protein_g = coalesce(plan_phase_goals.protein_g, excluded.protein_g),
  carbs_g = coalesce(plan_phase_goals.carbs_g, excluded.carbs_g),
  fat_g = coalesce(plan_phase_goals.fat_g, excluded.fat_g),
  fiber_g = coalesce(plan_phase_goals.fiber_g, excluded.fiber_g),
  fiber_min = coalesce(plan_phase_goals.fiber_min, excluded.fiber_min),
  fiber_max = coalesce(plan_phase_goals.fiber_max, excluded.fiber_max),
  steps_goal = coalesce(plan_phase_goals.steps_goal, excluded.steps_goal),
  target_weight_kg = coalesce(plan_phase_goals.target_weight_kg, excluded.target_weight_kg),
  target_body_fat_pct = coalesce(plan_phase_goals.target_body_fat_pct, excluded.target_body_fat_pct),
  target_muscle_mass_kg = coalesce(plan_phase_goals.target_muscle_mass_kg, excluded.target_muscle_mass_kg),
  rate_min_kg_wk = coalesce(plan_phase_goals.rate_min_kg_wk, excluded.rate_min_kg_wk),
  rate_max_kg_wk = coalesce(plan_phase_goals.rate_max_kg_wk, excluded.rate_max_kg_wk),
  body_fat_ceiling_pct = coalesce(plan_phase_goals.body_fat_ceiling_pct, excluded.body_fat_ceiling_pct);

-- ── 7 · plan_phase_volume — the weekly set targets, per plan and phase ─────
insert into public.plan_phase_volume (user_id, plan_id, phase, muscle, target_sets) values
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Chest', 11),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Lats', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Upper back', 4),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Lower back', 1),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Front delts', 4),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Side delts', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Rear delts', 2),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Biceps', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Triceps', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Forearms', 4),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Quads', 10),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Hamstrings', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Glutes', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Adductors', 0),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Calves', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'cut', 'Abs/core', 10),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Chest', 13),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Lats', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Upper back', 5),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Lower back', 1),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Front delts', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Side delts', 9),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Rear delts', 3),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Biceps', 9),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Triceps', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Forearms', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Quads', 12),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Hamstrings', 9),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Glutes', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Adductors', 2),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Calves', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx5', 'bulk', 'Abs/core', 11),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Chest', 11),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Lats', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Upper back', 4),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Lower back', 1),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Front delts', 4),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Side delts', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Rear delts', 2),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Biceps', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Triceps', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Forearms', 4),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Quads', 10),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Hamstrings', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Glutes', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Adductors', 0),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Calves', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'cut', 'Abs/core', 10),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Chest', 13),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Lats', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Upper back', 5),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Lower back', 1),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Front delts', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Side delts', 9),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Rear delts', 3),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Biceps', 9),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Triceps', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Forearms', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Quads', 12),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Hamstrings', 9),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Glutes', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Adductors', 2),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Calves', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'onyx4', 'bulk', 'Abs/core', 11),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Chest', 11),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Lats', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Upper back', 4),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Lower back', 1),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Front delts', 4),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Side delts', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Rear delts', 2),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Biceps', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Triceps', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Forearms', 4),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Quads', 10),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Hamstrings', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Glutes', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Adductors', 0),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Calves', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'cut', 'Abs/core', 10),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Chest', 13),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Lats', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Upper back', 5),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Lower back', 1),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Front delts', 6),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Side delts', 9),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Rear delts', 3),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Biceps', 9),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Triceps', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Forearms', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Quads', 12),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Hamstrings', 9),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Glutes', 7),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Adductors', 2),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Calves', 8),
  ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'ppl', 'bulk', 'Abs/core', 11)
on conflict (user_id, plan_id, phase, muscle) do nothing;

-- ── 8 · personal_records — the asserted floors, netted, session-less ────────
-- `achieved_on` is the book's date. A row only moves UP: an axis Onyx has since beaten keeps its record.
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Calf Press', 'weight', 72.5, null, 72.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Incline DB Press', 'volume', 432, 12, 36, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Lat Pulldown', 'weight', 49.5, null, 49.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Lat Pulldown', 'e1rm', 67.81, 13, 45, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Lat Pulldown', 'volume', 585, 13, 45, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Leg Extension', 'weight', 42.5, null, 42.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Leg Extension', 'e1rm', 59.86, 16, 37.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Leg Extension', 'volume', 600, 16, 37.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Leg Press', 'weight', 80, null, 80, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Leg Press', 'e1rm', 109.59, 14, 70, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Leg Press', 'volume', 980, 14, 70, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Overhead Triceps Extension', 'weight', 12.5, null, 12.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Pec Deck', 'weight', 55, null, 55, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Pec Deck', 'e1rm', 75.34, 15, 50, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Rope Triceps Pushdown', 'e1rm', 22.5, 15, 15, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Rope Triceps Pushdown', 'volume', 225, 15, 15, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Seated Cable Row (V-Grip)', 'e1rm', 62.3, 14, 42.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Seated Cable Row (V-Grip)', 'volume', 595, 14, 42.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Seated Leg Curl', 'weight', 50, null, 50, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Seated Leg Curl', 'e1rm', 73.53, 15, 47.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Seated Leg Curl', 'volume', 712.5, 15, 47.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Shoulder Press', 'weight', 31, null, 31, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Shoulder Press', 'e1rm', 42.25, 12, 30, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Straight-Arm Pulldown', 'weight', 17.5, null, 17.5, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;
insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
values ('f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Straight-Arm Pulldown', 'e1rm', 24.65, 15, 16.25, null, '2026-08-10')
on conflict (user_id, exercise_key, axis) do update set
  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
  session_id = null, achieved_on = excluded.achieved_on
where personal_records.value < excluded.value;

-- ── 9 · custom_supplements — the seed, only where an item key is absent ────
insert into public.custom_supplements (user_id, name, dose, color, time, schedule)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Two Per Day Multivitamin', '1 tab', '#3E9E7A', '10:30', '{"key":"multivitamin","notes":"2 tabs on Monday & Friday (Leg Days)","slot":"Morning"}'::jsonb
 where not exists (select 1 from public.custom_supplements
                    where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and schedule->>'key' = 'multivitamin');
insert into public.custom_supplements (user_id, name, dose, color, time, schedule)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Vitamin D3 + K2', '125 mcg', '#3E9E7A', '10:30', '{"key":"d3k2","slot":"Morning"}'::jsonb
 where not exists (select 1 from public.custom_supplements
                    where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and schedule->>'key' = 'd3k2');
insert into public.custom_supplements (user_id, name, dose, color, time, schedule)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'L-Citrulline', '3 g', '#8E9AAC', '11:45', '{"key":"citrulline","slot":"Pre-Workout","trainingOnly":true}'::jsonb
 where not exists (select 1 from public.custom_supplements
                    where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and schedule->>'key' = 'citrulline');
insert into public.custom_supplements (user_id, name, dose, color, time, schedule)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Nutricost Caffeine', '200 mg', '#8E9AAC', '11:45', '{"key":"caffeine","slot":"Pre-Workout","trainingOnly":true}'::jsonb
 where not exists (select 1 from public.custom_supplements
                    where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and schedule->>'key' = 'caffeine');
insert into public.custom_supplements (user_id, name, dose, color, time, schedule)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Creatine Monohydrate', '5 g', '#3D7AB8', '15:00', '{"key":"creatine","slot":"Lunch / Post-Workout"}'::jsonb
 where not exists (select 1 from public.custom_supplements
                    where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and schedule->>'key' = 'creatine');
insert into public.custom_supplements (user_id, name, dose, color, time, schedule)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Omega-3 Fish Oil', '2 caps', '#3D7AB8', '15:00', '{"key":"omega3","slot":"Lunch / Post-Workout"}'::jsonb
 where not exists (select 1 from public.custom_supplements
                    where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and schedule->>'key' = 'omega3');
insert into public.custom_supplements (user_id, name, dose, color, time, schedule)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Magnesium Glycinate', '300 mg', '#8A6FA8', '22:00', '{"key":"magnesium","slot":"Before Bed"}'::jsonb
 where not exists (select 1 from public.custom_supplements
                    where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and schedule->>'key' = 'magnesium');
insert into public.custom_supplements (user_id, name, dose, color, time, schedule)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'Glycine', '5 g', '#8A6FA8', '22:00', '{"key":"glycine","slot":"Before Bed"}'::jsonb
 where not exists (select 1 from public.custom_supplements
                    where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and schedule->>'key' = 'glycine');
insert into public.custom_supplements (user_id, name, dose, color, time, schedule)
select 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid, 'L-Theanine', '200 mg', '#8A6FA8', '22:00', '{"key":"theanine","slot":"Before Bed"}'::jsonb
 where not exists (select 1 from public.custom_supplements
                    where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and schedule->>'key' = 'theanine');

-- ── 10 · exercises.slug — where a deck spells a movement differently from its catalogue row ──
-- none: every deck movement's name matches its catalogue row exactly, so the DDL's backfill already wrote the right slug.

commit;

-- ── VERIFY ───────────────────────────────────────────────────────────────────
select 'plans' as t, count(*) from public.plans where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid
union all select 'routines', count(*) from public.routines where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid
union all select 'plan_phases', count(*) from public.plan_phases where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid
union all select 'lever_periods', count(*) from public.lever_periods where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid
union all select 'target_profiles (rungs)', count(*) from public.target_profiles where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and kind <> 'day'
union all select 'plan_phase_goals', count(*) from public.plan_phase_goals where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid
union all select 'plan_phase_volume', count(*) from public.plan_phase_volume where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid
union all select 'personal_records (floors)', count(*) from public.personal_records where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and session_id is null
union all select 'exercises with slug', count(*) from public.exercises where user_id = 'f405d57b-d09f-4a2e-8a33-0c112f2ec34c'::uuid and slug is not null
union all select 'other account rows', (
  select count(*) from public.routines where user_id = '21c7b986-42c4-4e8b-b770-5e119677084e')
  + (select count(*) from public.plan_phases where user_id = '21c7b986-42c4-4e8b-b770-5e119677084e')
  + (select count(*) from public.lever_periods where user_id = '21c7b986-42c4-4e8b-b770-5e119677084e');
-- Expect: plans 3 · routines 14 · plan_phases 8 · lever_periods 5 · rungs 4 · plan_phase_goals 6 ·
--         plan_phase_volume 96 · floors ≥ 12 · slugs 46 · other account 0.
