// GENERATED by scripts/gen-mirror-swift.mjs — DO NOT EDIT.
//
// Source: native/schema/supabase.json (introspected 2026-09-03).
// Edit the fixture and re-run `npm run mirror`; `npm run check:mirror`
// fails the build when this file and the fixture disagree.

import Foundation
import GRDB

// MARK: - daily_logs

/// Mirrors `public.daily_logs` (daily). Delta by `updated_at`.
public struct DailyLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "daily_logs"

    public var id: String
    public var userId: String
    public var date: String
    public var steps: Int?
    public var waterMl: Double?
    public var sleepMinutes: Int?
    public var carbsG: Double?
    public var proteinG: Double?
    public var fatsG: Double?
    public var weightKg: Double?
    public var leanMassKg: Double?
    public var bmi: Double?
    public var trainingMinutes: Int?
    public var activeEnergy: Double?
    public var bodyFatPct: Double?
    public var standingMinutes: Int?
    public var avgHeartRate: Int?
    public var avgRestHeartRate: Int?
    public var respiratoryRate: Double?
    public var bloodOxygen: Double?
    public var musclePercent: Double?
    public var waterPercent: Double?
    public var boneMineral: Double?
    public var visceralFat: Double?
    public var bmr: Double?
    public var createdAt: Date
    public var updatedAt: Date
    public var hrvMs: Double?
    public var exerciseMinutes: Int?
    public var standHours: Int?
    public var vo2max: Double?
    public var wristTempDelta: Double?
    public var timeInDaylightMin: Int?
    public var effortRating: Int?
    public var mood: Int?
    public var journalMd: String?
    public var distanceM: Double?
    public var proteinPercent: Double?
    public var muscleMassKg: Double?
    public var waterMassKg: Double?
    public var fatMassKg: Double?
    public var boneMineralKg: Double?
    public var proteinMassKg: Double?
    public var fatFreeMassKg: Double?
    public var weighinSkipReason: String?
    public var skeletalMuscleMassKg: Double?
    public var estimatedWaistToHipRatio: Double?
    public var nutritionException: String?
    public var nutritionEstimated: Bool
    public var sleepOnsetTrouble: Bool

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case steps
        case waterMl = "water_ml"
        case sleepMinutes = "sleep_minutes"
        case carbsG = "carbs_g"
        case proteinG = "protein_g"
        case fatsG = "fats_g"
        case weightKg = "weight_kg"
        case leanMassKg = "lean_mass_kg"
        case bmi
        case trainingMinutes = "training_minutes"
        case activeEnergy = "active_energy"
        case bodyFatPct = "body_fat_pct"
        case standingMinutes = "standing_minutes"
        case avgHeartRate = "avg_heart_rate"
        case avgRestHeartRate = "avg_rest_heart_rate"
        case respiratoryRate = "respiratory_rate"
        case bloodOxygen = "blood_oxygen"
        case musclePercent = "muscle_percent"
        case waterPercent = "water_percent"
        case boneMineral = "bone_mineral"
        case visceralFat = "visceral_fat"
        case bmr
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case hrvMs = "hrv_ms"
        case exerciseMinutes = "exercise_minutes"
        case standHours = "stand_hours"
        case vo2max
        case wristTempDelta = "wrist_temp_delta"
        case timeInDaylightMin = "time_in_daylight_min"
        case effortRating = "effort_rating"
        case mood
        case journalMd = "journal_md"
        case distanceM = "distance_m"
        case proteinPercent = "protein_percent"
        case muscleMassKg = "muscle_mass_kg"
        case waterMassKg = "water_mass_kg"
        case fatMassKg = "fat_mass_kg"
        case boneMineralKg = "bone_mineral_kg"
        case proteinMassKg = "protein_mass_kg"
        case fatFreeMassKg = "fat_free_mass_kg"
        case weighinSkipReason = "weighin_skip_reason"
        case skeletalMuscleMassKg = "skeletal_muscle_mass_kg"
        case estimatedWaistToHipRatio = "estimated_waist_to_hip_ratio"
        case nutritionException = "nutrition_exception"
        case nutritionEstimated = "nutrition_estimated"
        case sleepOnsetTrouble = "sleep_onset_trouble"
    }
}

// MARK: - daily_metrics

/// Mirrors `public.daily_metrics` (daily). Delta by `updated_at`.
public struct DailyMetricRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "daily_metrics"

    public var id: String
    public var userId: String
    public var date: String
    public var steps: Int?
    public var activeCal: Int?
    public var restHr: Int?
    public var createdAt: Date
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case steps
        case activeCal = "active_cal"
        case restHr = "rest_hr"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

// MARK: - daily_scores

/// Mirrors `public.daily_scores` (daily). Windowed on `date`.
public struct DailyScoreRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "daily_scores"

    public var id: String
    public var userId: String
    public var date: String
    public var score: Int
    public var sleepScore: Int?
    public var nutritionScore: Int?
    public var activityScore: Int?
    public var workoutScore: Int?
    public var recoveryScore: Int?
    public var batteryPct: Int?
    public var computedAt: Date
    public var finalized: Bool

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case score
        case sleepScore = "sleep_score"
        case nutritionScore = "nutrition_score"
        case activityScore = "activity_score"
        case workoutScore = "workout_score"
        case recoveryScore = "recovery_score"
        case batteryPct = "battery_pct"
        case computedAt = "computed_at"
        case finalized
    }
}

// MARK: - daily_targets

/// Mirrors `public.daily_targets` (daily). Delta by `updated_at`.
public struct DailyTargetRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "daily_targets"

    public var userId: String
    public var date: String
    public var kcal: Int?
    public var proteinG: Int?
    public var carbsG: Int?
    public var fatG: Int?
    public var stepsGoal: Int?
    public var note: String?
    public var updatedAt: Date
    public var profileKey: String?
    public var trackCarbs: Bool
    public var trackFat: Bool

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case date
        case kcal
        case proteinG = "protein_g"
        case carbsG = "carbs_g"
        case fatG = "fat_g"
        case stepsGoal = "steps_goal"
        case note
        case updatedAt = "updated_at"
        case profileKey = "profile_key"
        case trackCarbs = "track_carbs"
        case trackFat = "track_fat"
    }
}

// MARK: - nutrition_entries

/// Mirrors `public.nutrition_entries` (daily). Windowed on `date`.
public struct NutritionEntryRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "nutrition_entries"

    public var id: String
    public var userId: String
    public var hkUuid: String?
    public var loggedAt: Date
    public var date: String
    public var mealType: String?
    public var calories: Double
    public var proteinG: Double
    public var carbsG: Double
    public var fatG: Double
    public var fiberG: Double?
    public var phase: String?
    public var createdAt: Date
    public var targetKcal: Int?
    public var micros: JSONText?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case hkUuid = "hk_uuid"
        case loggedAt = "logged_at"
        case date
        case mealType = "meal_type"
        case calories
        case proteinG = "protein_g"
        case carbsG = "carbs_g"
        case fatG = "fat_g"
        case fiberG = "fiber_g"
        case phase
        case createdAt = "created_at"
        case targetKcal = "target_kcal"
        case micros
    }
}

// MARK: - water_intake

/// Mirrors `public.water_intake` (daily). Windowed on `date`.
public struct WaterIntakeRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "water_intake"

    public var id: String
    public var userId: String
    public var hkUuid: String?
    public var loggedAt: Date
    public var date: String
    public var amountMl: Double
    public var createdAt: Date

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case hkUuid = "hk_uuid"
        case loggedAt = "logged_at"
        case date
        case amountMl = "amount_ml"
        case createdAt = "created_at"
    }
}

// MARK: - supplement_log

/// Mirrors `public.supplement_log` (daily). Delta by `updated_at`.
public struct SupplementLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "supplement_log"

    public var userId: String
    public var date: String
    public var itemKey: String
    public var taken: Bool
    public var takenAt: Date?
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case date
        case itemKey = "item_key"
        case taken
        case takenAt = "taken_at"
        case updatedAt = "updated_at"
    }
}

// MARK: - supplement_dose_overrides

/// Mirrors `public.supplement_dose_overrides` (daily). Windowed on `date`.
public struct SupplementDoseOverrideRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "supplement_dose_overrides"

    public var userId: String
    public var date: String
    public var supplementKey: String
    public var dose: String

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case date
        case supplementKey = "supplement_key"
        case dose
    }
}

// MARK: - custom_supplements

/// Mirrors `public.custom_supplements` (daily). Pulled whole.
public struct CustomSupplementRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "custom_supplements"

    public var id: String
    public var userId: String
    public var name: String
    public var dose: String
    public var color: String?
    public var form: String?
    public var time: String?
    public var schedule: JSONText?
    public var micros: JSONText?
    public var createdAt: Date?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case name
        case dose
        case color
        case form
        case time
        case schedule
        case micros
        case createdAt = "created_at"
    }
}

// MARK: - fatigue_logs

/// Mirrors `public.fatigue_logs` (daily). Windowed on `date`.
public struct FatigueLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "fatigue_logs"

    public var id: String
    public var userId: String
    public var date: String
    public var slot: String
    public var level: Int
    public var note: String?
    public var createdAt: Date?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case slot
        case level
        case note
        case createdAt = "created_at"
    }
}

// MARK: - doms_logs

/// Mirrors `public.doms_logs` (daily). Windowed on `date`.
public struct DomsLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "doms_logs"

    public var id: String
    public var userId: String
    public var date: String
    public var muscleGroup: String
    public var severity: Int
    public var createdAt: Date?
    public var sourceSessionId: String?
    public var sourceDayKey: String?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case muscleGroup = "muscle_group"
        case severity
        case createdAt = "created_at"
        case sourceSessionId = "source_session_id"
        case sourceDayKey = "source_day_key"
    }
}

// MARK: - body_composition

/// Mirrors `public.body_composition` (body). Windowed on `date`.
public struct BodyCompositionRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "body_composition"

    public var id: String
    public var userId: String
    public var hkUuid: String?
    public var measuredAt: Date
    public var date: String
    public var weightKg: Double
    public var bodyFatPct: Double?
    public var muscleMassKg: Double?
    public var waterPct: Double?
    public var boneMassKg: Double?
    public var bmi: Double?
    public var createdAt: Date
    public var fatMassKg: Double?
    public var bodyWaterMassKg: Double?
    public var proteinMassKg: Double?
    public var musclePct: Double?
    public var proteinPct: Double?
    public var boneMineralPct: Double?
    public var skeletalMuscleMassKg: Double?
    public var fatFreeMassKg: Double?
    public var visceralFat: Double?
    public var bmr: Double?
    public var estimatedWaistToHipRatio: Double?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case hkUuid = "hk_uuid"
        case measuredAt = "measured_at"
        case date
        case weightKg = "weight_kg"
        case bodyFatPct = "body_fat_pct"
        case muscleMassKg = "muscle_mass_kg"
        case waterPct = "water_pct"
        case boneMassKg = "bone_mass_kg"
        case bmi
        case createdAt = "created_at"
        case fatMassKg = "fat_mass_kg"
        case bodyWaterMassKg = "body_water_mass_kg"
        case proteinMassKg = "protein_mass_kg"
        case musclePct = "muscle_pct"
        case proteinPct = "protein_pct"
        case boneMineralPct = "bone_mineral_pct"
        case skeletalMuscleMassKg = "skeletal_muscle_mass_kg"
        case fatFreeMassKg = "fat_free_mass_kg"
        case visceralFat = "visceral_fat"
        case bmr
        case estimatedWaistToHipRatio = "estimated_waist_to_hip_ratio"
    }
}

// MARK: - sleep_sessions

/// Mirrors `public.sleep_sessions` (body). Windowed on `start_time`.
public struct SleepSessionRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "sleep_sessions"

    public var id: String
    public var userId: String
    public var hkUuid: String?
    public var startTime: Date
    public var endTime: Date
    public var durationMin: Int
    public var deepMin: Int?
    public var remMin: Int?
    public var coreMin: Int?
    public var awakeMin: Int?
    public var sleepScore: Int?
    public var createdAt: Date

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case hkUuid = "hk_uuid"
        case startTime = "start_time"
        case endTime = "end_time"
        case durationMin = "duration_min"
        case deepMin = "deep_min"
        case remMin = "rem_min"
        case coreMin = "core_min"
        case awakeMin = "awake_min"
        case sleepScore = "sleep_score"
        case createdAt = "created_at"
    }
}

// MARK: - cardio_logs

/// Mirrors `public.cardio_logs` (body). Windowed on `date`.
public struct CardioLogRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "cardio_logs"

    public var id: String
    public var userId: String
    public var date: String
    public var kind: String
    public var distanceM: Double?
    public var durationMin: Double?
    public var kcal: Double?
    public var fromHealthkit: Bool?
    public var createdAt: Date?
    public var activeKcal: Double?
    public var totalKcal: Double?
    public var avgHr: Double?
    public var effort: Double?
    public var sessionId: String?
    public var inclinePct: Double?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case date
        case kind
        case distanceM = "distance_m"
        case durationMin = "duration_min"
        case kcal
        case fromHealthkit = "from_healthkit"
        case createdAt = "created_at"
        case activeKcal = "active_kcal"
        case totalKcal = "total_kcal"
        case avgHr = "avg_hr"
        case effort
        case sessionId = "session_id"
        case inclinePct = "incline_pct"
    }
}

// MARK: - personal_records

/// Mirrors `public.personal_records` (training). Delta by `updated_at`.
public struct PersonalRecordRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "personal_records"

    public var userId: String
    public var exerciseKey: String
    public var axis: String
    public var value: Double
    public var reps: Int?
    public var weightKg: Double?
    public var sessionId: String?
    public var achievedOn: String
    public var updatedAt: Date?

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case exerciseKey = "exercise_key"
        case axis
        case value
        case reps
        case weightKg = "weight_kg"
        case sessionId = "session_id"
        case achievedOn = "achieved_on"
        case updatedAt = "updated_at"
    }
}

// MARK: - routine_templates

/// Mirrors `public.routine_templates` (training). Delta by `updated_at`.
public struct RoutineTemplateRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "routine_templates"

    public var userId: String
    public var dayKey: String
    public var payload: JSONText
    public var sourceSessionId: String?
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case dayKey = "day_key"
        case payload
        case sourceSessionId = "source_session_id"
        case updatedAt = "updated_at"
    }
}

// MARK: - user_goals

/// Mirrors `public.user_goals` (plan). Delta by `updated_at`.
public struct UserGoalRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "user_goals"

    public var id: String
    public var userId: String
    public var sleepGoalHours: Double?
    public var calorieGoal: Int?
    public var proteinGoalG: Int?
    public var carbsGoalG: Int?
    public var fatGoalG: Int?
    public var stepsGoal: Int?
    public var activeCalGoal: Int?
    public var waterGoalMl: Int?
    public var contextMode: String
    public var goalPreset: String?
    public var createdAt: Date
    public var updatedAt: Date
    public var autoLogSupplements: Bool
    public var activeProgram: String
    public var dayCutoffHour: Int
    public var unitSystem: String
    public var reduceMotion: Bool
    public var timezone: String
    public var targetWeightKg: Double?
    public var weekEndDay: Int?
    public var activePlan: String?
    public var targetBodyFatPct: Double?
    public var targetMuscleMassKg: Double?
    public var activePhase: String?
    public var phaseStartedOn: String?
    public var trackRpe: Bool
    public var activeLever: String?
    public var contextSince: String?
    public var maintenanceUntil: String?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case sleepGoalHours = "sleep_goal_hours"
        case calorieGoal = "calorie_goal"
        case proteinGoalG = "protein_goal_g"
        case carbsGoalG = "carbs_goal_g"
        case fatGoalG = "fat_goal_g"
        case stepsGoal = "steps_goal"
        case activeCalGoal = "active_cal_goal"
        case waterGoalMl = "water_goal_ml"
        case contextMode = "context_mode"
        case goalPreset = "goal_preset"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case autoLogSupplements = "auto_log_supplements"
        case activeProgram = "active_program"
        case dayCutoffHour = "day_cutoff_hour"
        case unitSystem = "unit_system"
        case reduceMotion = "reduce_motion"
        case timezone
        case targetWeightKg = "target_weight_kg"
        case weekEndDay = "week_end_day"
        case activePlan = "active_plan"
        case targetBodyFatPct = "target_body_fat_pct"
        case targetMuscleMassKg = "target_muscle_mass_kg"
        case activePhase = "active_phase"
        case phaseStartedOn = "phase_started_on"
        case trackRpe = "track_rpe"
        case activeLever = "active_lever"
        case contextSince = "context_since"
        case maintenanceUntil = "maintenance_until"
    }
}

// MARK: - target_profiles

/// Mirrors `public.target_profiles` (plan). Delta by `updated_at`.
public struct TargetProfileRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "target_profiles"

    public var userId: String
    public var key: String
    public var label: String
    public var summary: String?
    public var sort: Int
    public var kcal: Int?
    public var proteinG: Int?
    public var carbsG: Int?
    public var fatG: Int?
    public var stepsGoal: Int?
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case key
        case label
        case summary
        case sort
        case kcal
        case proteinG = "protein_g"
        case carbsG = "carbs_g"
        case fatG = "fat_g"
        case stepsGoal = "steps_goal"
        case updatedAt = "updated_at"
    }
}

// MARK: - plans

/// Mirrors `public.plans` (plan). Pulled whole.
public struct PlanRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "plans"

    public var id: String
    public var userId: String
    public var name: String
    public var programId: String?
    public var active: Bool?
    public var startedOn: String?
    public var createdAt: Date?

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case name
        case programId = "program_id"
        case active
        case startedOn = "started_on"
        case createdAt = "created_at"
    }
}

// MARK: - plan_phase_goals

/// Mirrors `public.plan_phase_goals` (plan). Delta by `updated_at`.
public struct PlanPhaseGoalRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "plan_phase_goals"

    public var userId: String
    public var planId: String
    public var phase: String
    public var kcal: Int?
    public var proteinG: Int?
    public var carbsG: Int?
    public var fatG: Int?
    public var fiberMin: Int?
    public var fiberMax: Int?
    public var updatedAt: Date?
    public var stepsGoal: Int?
    public var targetWeightKg: Double?
    public var targetBodyFatPct: Double?
    public var targetMuscleMassKg: Double?
    public var rateMinKgWk: Double?
    public var rateMaxKgWk: Double?

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case planId = "plan_id"
        case phase
        case kcal
        case proteinG = "protein_g"
        case carbsG = "carbs_g"
        case fatG = "fat_g"
        case fiberMin = "fiber_min"
        case fiberMax = "fiber_max"
        case updatedAt = "updated_at"
        case stepsGoal = "steps_goal"
        case targetWeightKg = "target_weight_kg"
        case targetBodyFatPct = "target_body_fat_pct"
        case targetMuscleMassKg = "target_muscle_mass_kg"
        case rateMinKgWk = "rate_min_kg_wk"
        case rateMaxKgWk = "rate_max_kg_wk"
    }
}

// MARK: - plan_phase_volume

/// Mirrors `public.plan_phase_volume` (plan). Delta by `updated_at`.
public struct PlanPhaseVolumeRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "plan_phase_volume"

    public var userId: String
    public var planId: String
    public var phase: String
    public var muscle: String
    public var targetSets: Int
    public var updatedAt: Date?

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case planId = "plan_id"
        case phase
        case muscle
        case targetSets = "target_sets"
        case updatedAt = "updated_at"
    }
}

// MARK: - program_day_layout

/// Mirrors `public.program_day_layout` (plan). Delta by `updated_at`.
public struct ProgramDayLayoutRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "program_day_layout"

    public var userId: String
    public var programId: String
    public var layout: JSONText
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case programId = "program_id"
        case layout
        case updatedAt = "updated_at"
    }
}

// MARK: - schedule_overrides

/// Mirrors `public.schedule_overrides` (plan). Delta by `updated_at`.
public struct ScheduleOverrideRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "schedule_overrides"

    public var userId: String
    public var date: String
    public var dayKey: String
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case date
        case dayKey = "day_key"
        case updatedAt = "updated_at"
    }
}

// MARK: - dashboard_layouts

/// Mirrors `public.dashboard_layouts` (plan). Delta by `updated_at`.
public struct DashboardLayoutRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "dashboard_layouts"

    public var userId: String
    public var layout: JSONText
    public var updatedAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case layout
        case updatedAt = "updated_at"
    }
}

// MARK: - profiles

/// Mirrors `public.profiles` (plan). Delta by `updated_at`.
public struct ProfileRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "profiles"

    public var userId: String
    public var displayName: String?
    public var role: String
    public var updatedAt: Date
    public var createdAt: Date

    public enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case displayName = "display_name"
        case role
        case updatedAt = "updated_at"
        case createdAt = "created_at"
    }
}

// MARK: - reports

/// Mirrors `public.reports` (reports). Pulled whole.
public struct ReportRow: Codable, FetchableRecord, PersistableRecord, Sendable, Equatable {
    public static let databaseTableName = "reports"

    public var id: String
    public var userId: String
    public var type: String
    public var periodStart: String
    public var periodEnd: String
    public var contentMd: String?
    public var sessionSummaryMd: String?
    public var weightReportMd: String?
    public var metrics: JSONText?
    public var notionPageId: String?
    public var createdAt: Date

    public enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case type
        case periodStart = "period_start"
        case periodEnd = "period_end"
        case contentMd = "content_md"
        case sessionSummaryMd = "session_summary_md"
        case weightReportMd = "weight_report_md"
        case metrics
        case notionPageId = "notion_page_id"
        case createdAt = "created_at"
    }
}

// MARK: - Schema

extension AppDatabase {
    /// The mirror's tables, as one migration.
    ///
    /// Registered by `AppDatabase.migrator`. Append-only like every other
    /// migration here: a regenerated schema is a NEW migration, never an edit
    /// to this one, because an edited migration runs on a fresh install and
    /// not on yours.
    static func migrateMirrorV1(_ db: Database) throws {
            try db.create(table: "daily_logs") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("steps", .integer)
                t.column("water_ml", .double)
                t.column("sleep_minutes", .integer)
                t.column("carbs_g", .double)
                t.column("protein_g", .double)
                t.column("fats_g", .double)
                t.column("weight_kg", .double)
                t.column("lean_mass_kg", .double)
                t.column("bmi", .double)
                t.column("training_minutes", .integer)
                t.column("active_energy", .double)
                t.column("body_fat_pct", .double)
                t.column("standing_minutes", .integer)
                t.column("avg_heart_rate", .integer)
                t.column("avg_rest_heart_rate", .integer)
                t.column("respiratory_rate", .double)
                t.column("blood_oxygen", .double)
                t.column("muscle_percent", .double)
                t.column("water_percent", .double)
                t.column("bone_mineral", .double)
                t.column("visceral_fat", .double)
                t.column("bmr", .double)
                t.column("created_at", .datetime).notNull()
                t.column("updated_at", .datetime).notNull()
                t.column("hrv_ms", .double)
                t.column("exercise_minutes", .integer)
                t.column("stand_hours", .integer)
                t.column("vo2max", .double)
                t.column("wrist_temp_delta", .double)
                t.column("time_in_daylight_min", .integer)
                t.column("effort_rating", .integer)
                t.column("mood", .integer)
                t.column("journal_md", .text)
                t.column("distance_m", .double)
                t.column("protein_percent", .double)
                t.column("muscle_mass_kg", .double)
                t.column("water_mass_kg", .double)
                t.column("fat_mass_kg", .double)
                t.column("bone_mineral_kg", .double)
                t.column("protein_mass_kg", .double)
                t.column("fat_free_mass_kg", .double)
                t.column("weighin_skip_reason", .text)
                t.column("skeletal_muscle_mass_kg", .double)
                t.column("estimated_waist_to_hip_ratio", .double)
                t.column("nutrition_exception", .text)
                t.column("nutrition_estimated", .boolean).notNull()
                t.column("sleep_onset_trouble", .boolean).notNull()
            }
            try db.create(table: "daily_metrics") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("steps", .integer)
                t.column("active_cal", .integer)
                t.column("rest_hr", .integer)
                t.column("created_at", .datetime).notNull()
                t.column("updated_at", .datetime).notNull()
            }
            try db.create(table: "daily_scores") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("score", .integer).notNull()
                t.column("sleep_score", .integer)
                t.column("nutrition_score", .integer)
                t.column("activity_score", .integer)
                t.column("workout_score", .integer)
                t.column("recovery_score", .integer)
                t.column("battery_pct", .integer)
                t.column("computed_at", .datetime).notNull()
                t.column("finalized", .boolean).notNull()
            }
            try db.create(table: "daily_targets") { t in
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("kcal", .integer)
                t.column("protein_g", .integer)
                t.column("carbs_g", .integer)
                t.column("fat_g", .integer)
                t.column("steps_goal", .integer)
                t.column("note", .text)
                t.column("updated_at", .datetime).notNull()
                t.column("profile_key", .text)
                t.column("track_carbs", .boolean).notNull()
                t.column("track_fat", .boolean).notNull()
                t.primaryKey(["user_id", "date"])
            }
            try db.create(table: "nutrition_entries") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("hk_uuid", .text)
                t.column("logged_at", .datetime).notNull()
                t.column("date", .text).notNull()
                t.column("meal_type", .text)
                t.column("calories", .double).notNull()
                t.column("protein_g", .double).notNull()
                t.column("carbs_g", .double).notNull()
                t.column("fat_g", .double).notNull()
                t.column("fiber_g", .double)
                t.column("phase", .text)
                t.column("created_at", .datetime).notNull()
                t.column("target_kcal", .integer)
                t.column("micros", .text)
            }
            try db.create(table: "water_intake") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("hk_uuid", .text)
                t.column("logged_at", .datetime).notNull()
                t.column("date", .text).notNull()
                t.column("amount_ml", .double).notNull()
                t.column("created_at", .datetime).notNull()
            }
            try db.create(table: "supplement_log") { t in
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("item_key", .text).notNull()
                t.column("taken", .boolean).notNull()
                t.column("taken_at", .datetime)
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "date", "item_key"])
            }
            try db.create(table: "supplement_dose_overrides") { t in
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("supplement_key", .text).notNull()
                t.column("dose", .text).notNull()
                t.primaryKey(["user_id", "date", "supplement_key"])
            }
            try db.create(table: "custom_supplements") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("name", .text).notNull()
                t.column("dose", .text).notNull()
                t.column("color", .text)
                t.column("form", .text)
                t.column("time", .text)
                t.column("schedule", .text)
                t.column("micros", .text)
                t.column("created_at", .datetime)
            }
            try db.create(table: "fatigue_logs") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("slot", .text).notNull()
                t.column("level", .integer).notNull()
                t.column("note", .text)
                t.column("created_at", .datetime)
            }
            try db.create(table: "doms_logs") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("muscle_group", .text).notNull()
                t.column("severity", .integer).notNull()
                t.column("created_at", .datetime)
                t.column("source_session_id", .text)
                t.column("source_day_key", .text)
            }
            try db.create(table: "body_composition") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("hk_uuid", .text)
                t.column("measured_at", .datetime).notNull()
                t.column("date", .text).notNull()
                t.column("weight_kg", .double).notNull()
                t.column("body_fat_pct", .double)
                t.column("muscle_mass_kg", .double)
                t.column("water_pct", .double)
                t.column("bone_mass_kg", .double)
                t.column("bmi", .double)
                t.column("created_at", .datetime).notNull()
                t.column("fat_mass_kg", .double)
                t.column("body_water_mass_kg", .double)
                t.column("protein_mass_kg", .double)
                t.column("muscle_pct", .double)
                t.column("protein_pct", .double)
                t.column("bone_mineral_pct", .double)
                t.column("skeletal_muscle_mass_kg", .double)
                t.column("fat_free_mass_kg", .double)
                t.column("visceral_fat", .double)
                t.column("bmr", .double)
                t.column("estimated_waist_to_hip_ratio", .double)
            }
            try db.create(table: "sleep_sessions") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("hk_uuid", .text)
                t.column("start_time", .datetime).notNull()
                t.column("end_time", .datetime).notNull()
                t.column("duration_min", .integer).notNull()
                t.column("deep_min", .integer)
                t.column("rem_min", .integer)
                t.column("core_min", .integer)
                t.column("awake_min", .integer)
                t.column("sleep_score", .integer)
                t.column("created_at", .datetime).notNull()
            }
            try db.create(table: "cardio_logs") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("kind", .text).notNull()
                t.column("distance_m", .double)
                t.column("duration_min", .double)
                t.column("kcal", .double)
                t.column("from_healthkit", .boolean)
                t.column("created_at", .datetime)
                t.column("active_kcal", .double)
                t.column("total_kcal", .double)
                t.column("avg_hr", .double)
                t.column("effort", .double)
                t.column("session_id", .text)
                t.column("incline_pct", .double)
            }
            try db.create(table: "personal_records") { t in
                t.column("user_id", .text).notNull()
                t.column("exercise_key", .text).notNull()
                t.column("axis", .text).notNull()
                t.column("value", .double).notNull()
                t.column("reps", .integer)
                t.column("weight_kg", .double)
                t.column("session_id", .text)
                t.column("achieved_on", .text).notNull()
                t.column("updated_at", .datetime)
                t.primaryKey(["user_id", "exercise_key", "axis"])
            }
            try db.create(table: "routine_templates") { t in
                t.column("user_id", .text).notNull()
                t.column("day_key", .text).notNull()
                t.column("payload", .text).notNull()
                t.column("source_session_id", .text)
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "day_key"])
            }
            try db.create(table: "user_goals") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("sleep_goal_hours", .double)
                t.column("calorie_goal", .integer)
                t.column("protein_goal_g", .integer)
                t.column("carbs_goal_g", .integer)
                t.column("fat_goal_g", .integer)
                t.column("steps_goal", .integer)
                t.column("active_cal_goal", .integer)
                t.column("water_goal_ml", .integer)
                t.column("context_mode", .text).notNull()
                t.column("goal_preset", .text)
                t.column("created_at", .datetime).notNull()
                t.column("updated_at", .datetime).notNull()
                t.column("auto_log_supplements", .boolean).notNull()
                t.column("active_program", .text).notNull()
                t.column("day_cutoff_hour", .integer).notNull()
                t.column("unit_system", .text).notNull()
                t.column("reduce_motion", .boolean).notNull()
                t.column("timezone", .text).notNull()
                t.column("target_weight_kg", .double)
                t.column("week_end_day", .integer)
                t.column("active_plan", .text)
                t.column("target_body_fat_pct", .double)
                t.column("target_muscle_mass_kg", .double)
                t.column("active_phase", .text)
                t.column("phase_started_on", .text)
                t.column("track_rpe", .boolean).notNull()
                t.column("active_lever", .text)
                t.column("context_since", .text)
                t.column("maintenance_until", .text)
            }
            try db.create(table: "target_profiles") { t in
                t.column("user_id", .text).notNull()
                t.column("key", .text).notNull()
                t.column("label", .text).notNull()
                t.column("summary", .text)
                t.column("sort", .integer).notNull()
                t.column("kcal", .integer)
                t.column("protein_g", .integer)
                t.column("carbs_g", .integer)
                t.column("fat_g", .integer)
                t.column("steps_goal", .integer)
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "key"])
            }
            try db.create(table: "plans") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("name", .text).notNull()
                t.column("program_id", .text)
                t.column("active", .boolean)
                t.column("started_on", .text)
                t.column("created_at", .datetime)
            }
            try db.create(table: "plan_phase_goals") { t in
                t.column("user_id", .text).notNull()
                t.column("plan_id", .text).notNull()
                t.column("phase", .text).notNull()
                t.column("kcal", .integer)
                t.column("protein_g", .integer)
                t.column("carbs_g", .integer)
                t.column("fat_g", .integer)
                t.column("fiber_min", .integer)
                t.column("fiber_max", .integer)
                t.column("updated_at", .datetime)
                t.column("steps_goal", .integer)
                t.column("target_weight_kg", .double)
                t.column("target_body_fat_pct", .double)
                t.column("target_muscle_mass_kg", .double)
                t.column("rate_min_kg_wk", .double)
                t.column("rate_max_kg_wk", .double)
                t.primaryKey(["user_id", "plan_id", "phase"])
            }
            try db.create(table: "plan_phase_volume") { t in
                t.column("user_id", .text).notNull()
                t.column("plan_id", .text).notNull()
                t.column("phase", .text).notNull()
                t.column("muscle", .text).notNull()
                t.column("target_sets", .integer).notNull()
                t.column("updated_at", .datetime)
                t.primaryKey(["user_id", "plan_id", "phase", "muscle"])
            }
            try db.create(table: "program_day_layout") { t in
                t.column("user_id", .text).notNull()
                t.column("program_id", .text).notNull()
                t.column("layout", .text).notNull()
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "program_id"])
            }
            try db.create(table: "schedule_overrides") { t in
                t.column("user_id", .text).notNull()
                t.column("date", .text).notNull()
                t.column("day_key", .text).notNull()
                t.column("updated_at", .datetime).notNull()
                t.primaryKey(["user_id", "date"])
            }
            try db.create(table: "dashboard_layouts") { t in
                t.primaryKey("user_id", .text)
                t.column("layout", .text).notNull()
                t.column("updated_at", .datetime).notNull()
            }
            try db.create(table: "profiles") { t in
                t.primaryKey("user_id", .text)
                t.column("display_name", .text)
                t.column("role", .text).notNull()
                t.column("updated_at", .datetime).notNull()
                t.column("created_at", .datetime).notNull()
            }
            try db.create(table: "reports") { t in
                t.primaryKey("id", .text)
                t.column("user_id", .text).notNull()
                t.column("type", .text).notNull()
                t.column("period_start", .text).notNull()
                t.column("period_end", .text).notNull()
                t.column("content_md", .text)
                t.column("session_summary_md", .text)
                t.column("weight_report_md", .text)
                t.column("metrics", .text)
                t.column("notion_page_id", .text)
                t.column("created_at", .datetime).notNull()
            }
    }
}

/// Every mirrored table, with the strategy that keeps it current.
///
/// Generated, so the list cannot fall behind the schema fixture the way a
/// hand-maintained one would. `bespoke` tables are absent on purpose: they
/// land in tables the logger already owns, through `SyncTranslation`.
public enum MirrorCatalogue {
    public static let tables: [MirrorTable] = [
        MirrorTable(name: "daily_logs", group: .daily, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(DailyLogRow.self, from: $1) }),
        MirrorTable(name: "daily_metrics", group: .daily, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(DailyMetricRow.self, from: $1) }),
        MirrorTable(name: "daily_scores", group: .daily, strategy: .window(column: "date"),
                    pull: { try await $0.pull(DailyScoreRow.self, from: $1) }),
        MirrorTable(name: "daily_targets", group: .daily, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(DailyTargetRow.self, from: $1) }),
        MirrorTable(name: "nutrition_entries", group: .daily, strategy: .window(column: "date"),
                    pull: { try await $0.pull(NutritionEntryRow.self, from: $1) }),
        MirrorTable(name: "water_intake", group: .daily, strategy: .window(column: "date"),
                    pull: { try await $0.pull(WaterIntakeRow.self, from: $1) }),
        MirrorTable(name: "supplement_log", group: .daily, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(SupplementLogRow.self, from: $1) }),
        MirrorTable(name: "supplement_dose_overrides", group: .daily, strategy: .window(column: "date"),
                    pull: { try await $0.pull(SupplementDoseOverrideRow.self, from: $1) }),
        MirrorTable(name: "custom_supplements", group: .daily, strategy: .full,
                    pull: { try await $0.pull(CustomSupplementRow.self, from: $1) }),
        MirrorTable(name: "fatigue_logs", group: .daily, strategy: .window(column: "date"),
                    pull: { try await $0.pull(FatigueLogRow.self, from: $1) }),
        MirrorTable(name: "doms_logs", group: .daily, strategy: .window(column: "date"),
                    pull: { try await $0.pull(DomsLogRow.self, from: $1) }),
        MirrorTable(name: "body_composition", group: .body, strategy: .window(column: "date"),
                    pull: { try await $0.pull(BodyCompositionRow.self, from: $1) }),
        MirrorTable(name: "sleep_sessions", group: .body, strategy: .window(column: "start_time"),
                    pull: { try await $0.pull(SleepSessionRow.self, from: $1) }),
        MirrorTable(name: "cardio_logs", group: .body, strategy: .window(column: "date"),
                    pull: { try await $0.pull(CardioLogRow.self, from: $1) }),
        MirrorTable(name: "personal_records", group: .training, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(PersonalRecordRow.self, from: $1) }),
        MirrorTable(name: "routine_templates", group: .training, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(RoutineTemplateRow.self, from: $1) }),
        MirrorTable(name: "user_goals", group: .plan, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(UserGoalRow.self, from: $1) }),
        MirrorTable(name: "target_profiles", group: .plan, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(TargetProfileRow.self, from: $1) }),
        MirrorTable(name: "plans", group: .plan, strategy: .full,
                    pull: { try await $0.pull(PlanRow.self, from: $1) }),
        MirrorTable(name: "plan_phase_goals", group: .plan, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(PlanPhaseGoalRow.self, from: $1) }),
        MirrorTable(name: "plan_phase_volume", group: .plan, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(PlanPhaseVolumeRow.self, from: $1) }),
        MirrorTable(name: "program_day_layout", group: .plan, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(ProgramDayLayoutRow.self, from: $1) }),
        MirrorTable(name: "schedule_overrides", group: .plan, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(ScheduleOverrideRow.self, from: $1) }),
        MirrorTable(name: "dashboard_layouts", group: .plan, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(DashboardLayoutRow.self, from: $1) }),
        MirrorTable(name: "profiles", group: .plan, strategy: .delta(column: "updated_at"),
                    pull: { try await $0.pull(ProfileRow.self, from: $1) }),
        MirrorTable(name: "reports", group: .reports, strategy: .full,
                    pull: { try await $0.pull(ReportRow.self, from: $1) }),
    ]
}
