import Foundation
import Testing
import OnyxCore
@testable import OnyxData

// ─────────────────────────────────────────────────────────────────────────────
// W2 · THE SEED DUMP — the founder's constants, printed as SQL, once.
//
// `docs/sql/w2-seed-founder.sql` is GENERATED by this test from the live Swift
// constants (`Program.all`, `Phases.all`, `Levers.all` + `.schedule`,
// `Programs.cutTargets` / `.bulkTargets`, `PhaseGoals`, `PrTruth.floor(for:)`,
// `Supplements.protocolSeed`) so that not one number in the seed is typed by
// hand. Parity is by construction: the rows ARE the constants.
//
// The exercise uuids come from the founder's live catalogue, captured by the
// schema-truth-checker on 2026-09-10 and pinned below; the payload resolves
// each program movement through `ExerciseIndex` — the same exact-then-
// normalised rule the sync uses — so the routine row names the catalogue row
// the phone already files that movement's sets under.
//
// One-off: it writes only when `ONYX_SEED_OUT` names a file, and the
// constants it reads are deleted at the end of W2, taking this test with
// them. What it asserts without the env var is the part that must stay true
// of the file already checked in: every statement is scoped to the founder,
// and the second account gets nothing.
//
//   ONYX_SEED_OUT=docs/sql/w2-seed-founder.sql \
//   ONYX_TEMPLATES_OUT=native/Onyx/Resources/plan-templates.json \
//   npm run swift:data -- --filter SeedDumpTests
// ─────────────────────────────────────────────────────────────────────────────

struct SeedDumpTests {

    /// The founder's `auth.users.id`. The ONLY account the seed may touch:
    /// `21c7b986-42c4-4e8b-b770-5e119677084e` (created 2026-09-08) is a second
    /// account and must inherit nothing.
    static let founder = "f405d57b-d09f-4a2e-8a33-0c112f2ec34c"
    static let otherAccount = "21c7b986-42c4-4e8b-b770-5e119677084e"

    static let catalogue: [RemoteExercise] = [
    // Captured from the live catalogue on 2026-09-10 (schema-truth-checker); the founder's 46 rows.
    RemoteExercise(id: "6db37347-9651-4314-bb72-d2dde89cb7cb", name: "Behind-Back Wrist Curl"),
    RemoteExercise(id: "5047dc85-7e18-4181-96a6-b22af144440b", name: "Bicep Curl"),
    RemoteExercise(id: "f93628e8-d179-423d-82f0-4e3c5883a455", name: "Bicycle Crunch"),
    RemoteExercise(id: "66037198-a6b0-4af5-a7af-706c37e666cd", name: "Calf Press"),
    RemoteExercise(id: "61a4889c-5cd8-4c15-9918-14f023e615a0", name: "Calf Raise"),
    RemoteExercise(id: "81657991-ecd7-474b-a9c9-ccd2d7df4157", name: "Chest Press"),
    RemoteExercise(id: "73f5f54b-ae0e-4c94-93cd-15d7eb5811f6", name: "Cross-Body Cable Extension"),
    RemoteExercise(id: "8ee210f3-1cb2-4bba-9c08-e1305535cbc0", name: "Crunch Machine"),
    RemoteExercise(id: "3a3acfe4-4ffd-4bee-9884-f6b7b09223fa", name: "Face Pull"),
    RemoteExercise(id: "07e99254-df7f-463e-b9b2-bd11a0dd022a", name: "Hack Squat"),
    RemoteExercise(id: "e0031f39-97eb-4e5e-8672-7eb00d362c7e", name: "Hammer Curl"),
    RemoteExercise(id: "c6627399-f44e-4abb-97b8-ca0c36881843", name: "Hanging Knee Raise"),
    RemoteExercise(id: "c70b57b0-ab44-4a0f-bd58-6f2db8c37898", name: "Hip Adduction"),
    RemoteExercise(id: "2bdee111-02a7-4abc-9b58-877dabadd57c", name: "Hip Thrust"),
    RemoteExercise(id: "ac28ac9f-03fa-44cd-b139-95a20e827033", name: "Hollow Hold"),
    RemoteExercise(id: "335e4d62-7b82-4c9b-b78d-78cd1e7241fc", name: "Hollow Rock"),
    RemoteExercise(id: "d1bb00f2-f88d-4a6c-80b1-e6cd6f9136a2", name: "Incline DB Press"),
    RemoteExercise(id: "2eaa26ca-61d7-462c-92f4-45781c5869b4", name: "Lat Pulldown"),
    RemoteExercise(id: "57504cc2-37a2-4f05-badc-3b2afea1196f", name: "Lateral Raise"),
    RemoteExercise(id: "447184a0-e31e-4946-9791-826c32d57eef", name: "Leg Extension"),
    RemoteExercise(id: "918e8f8d-10b4-4609-9c86-b4df8ffba523", name: "Leg Press"),
    RemoteExercise(id: "0056e5b5-e97a-4487-a68a-0bdf71dc5d0f", name: "Lying Leg Raise"),
    RemoteExercise(id: "44ef3d06-c0c2-47b3-bedc-6860085b6622", name: "Neutral-Grip Lat Pulldown"),
    RemoteExercise(id: "c2bf052f-4128-40c0-a0db-d2d48df41f84", name: "Overhead Triceps Extension"),
    RemoteExercise(id: "33456a42-aa5b-43d9-87f7-f27c09298c40", name: "Pec Deck"),
    RemoteExercise(id: "57c6bd41-0456-4bb1-8d6b-7f6ff482089b", name: "Preacher Curl"),
    RemoteExercise(id: "b0763b58-4555-425d-802f-e7e6850194e4", name: "Reverse Crunch"),
    RemoteExercise(id: "5631ea58-b9e9-4b7e-93be-b89044d4ef97", name: "Reverse EZ-Bar Curl"),
    RemoteExercise(id: "ba5f3ca2-450c-4f92-a5fd-6870a36faf83", name: "Romanian Deadlift"),
    RemoteExercise(id: "de056933-d71e-44ee-97d6-65954dbf82a2", name: "Rope Triceps Pushdown"),
    RemoteExercise(id: "da0a4251-4603-4987-969e-33b47b399d09", name: "Russian Twist"),
    RemoteExercise(id: "71bd5b9d-a91c-43a1-876b-a8644e8a842f", name: "Seated Cable Row"),
    RemoteExercise(id: "8bd1aada-fa77-464e-960b-784647a95fcf", name: "Seated Cable Row (V-Grip)"),
    RemoteExercise(id: "2c397ee9-57af-4f84-9790-8552ecbda124", name: "Seated Cable Row (Wide Grip)"),
    RemoteExercise(id: "8cbc3b90-20e6-4b99-8124-1e0a01920ad3", name: "Seated DB Wrist Curl"),
    RemoteExercise(id: "227afcfc-3c38-4104-b5ca-1717a8f2e67e", name: "Seated Incline DB Curl"),
    RemoteExercise(id: "1cc784ad-3f4e-402d-9a3e-969770876bb3", name: "Seated Lateral Raise"),
    RemoteExercise(id: "be4ce30b-d143-487a-924e-3c25bc22154d", name: "Seated Leg Curl"),
    RemoteExercise(id: "40ce6b78-4e9b-4e2c-b5f0-5fdc2e9f1083", name: "Shoulder Press"),
    RemoteExercise(id: "57b224bc-fe35-41b1-b0a9-545734667084", name: "Side Plank"),
    RemoteExercise(id: "a213f4e3-093d-45d3-bdd4-959ee7a0db7b", name: "Single Arm Cable Crossover"),
    RemoteExercise(id: "c528edde-6a93-4e8a-a20a-325837d36174", name: "Single Arm Lateral Raise"),
    RemoteExercise(id: "22b483f9-1a57-4adb-99db-4e4504826ea6", name: "Single Arm Triceps Pushdown"),
    RemoteExercise(id: "9bb8032d-d093-4959-9774-7b4d62b211ae", name: "Single-Arm Cable Fly"),
    RemoteExercise(id: "04fdd423-cb00-46bb-a711-5c30a5dbec0e", name: "Straight-Arm Pulldown"),
    RemoteExercise(id: "26a32c8f-5fa5-4157-b869-e773ccb7ff3f", name: "Treadmill"),
    ]

    // MARK: - SQL helpers

    static func q(_ s: String) -> String { "'" + s.replacingOccurrences(of: "'", with: "''") + "'" }
    static func q(_ s: String?) -> String { s.map(q) ?? "null" }
    static func n(_ d: Double?) -> String {
        guard let d else { return "null" }
        return d == d.rounded() && abs(d) < 1e12 ? String(Int(d)) : String(d)
    }
    static func n(_ i: Int?) -> String { i.map(String.init) ?? "null" }
    static func b(_ v: Bool?) -> String { v.map { $0 ? "true" : "false" } ?? "null" }
    static var me: String { "'\(founder)'::uuid" }

    /// `[String: Any?]` → JSON, dropping the nils. `compactMapValues` over
    /// `Any` cannot see through an `Optional` boxed as `Any`, so this unboxes.
    static func compact(_ o: [String: Any?]) -> [String: Any] {
        var out: [String: Any] = [:]
        for (k, v) in o { if let v { out[k] = v } }
        return out
    }

    static func json(_ any: Any) throws -> String {
        let data = try JSONSerialization.data(withJSONObject: any, options: [.sortedKeys, .withoutEscapingSlashes])
        return String(decoding: data, as: UTF8.self)
    }

    // MARK: - The catalogue entries

    struct PlanEntry {
        var id: String, label: String, blurb: String, isLegacy: Bool, sort: Int, startedOn: String?
    }

    /// `Programs.all` in picker order, with the start dates the constants
    /// implied: PPL opened on its first phase (`Phases.all[0].start`); Onyx-5
    /// on the cut (`Era.onyxCutStart`); Onyx-4 was never started.
    static var plans: [PlanEntry] {
        Programs.pickerOrder.enumerated().map { i, p in
            PlanEntry(
                id: p.id, label: p.label, blurb: p.blurb, isLegacy: p.isLegacy, sort: i,
                startedOn: p.id == "onyx5" ? Era.onyxCutStart
                    : p.id == "ppl" ? Phases.all.first { $0.era == .ppl }?.start
                    : nil
            )
        }
    }

    /// The routine payload for one program day, exercise ids resolved.
    static func payload(_ day: ProgramDay, index: ExerciseIndex) -> [String: Any] {
        [
            "version": 1,
            "exercises": day.exercises.map { e -> [String: Any] in
                var o: [String: Any] = [
                    "name": e.name, "sets": e.sets, "reps": e.reps, "compound": e.isCompound,
                ]
                if let id = try? index.id(forName: e.name) { o["exerciseId"] = id }
                if let c = e.cutSets { o["cutSets"] = c }
                if let r = e.restSec { o["restSec"] = r }
                if let w = e.wk1Kg { o["wk1Kg"] = w }
                if let note = e.note { o["note"] = note }
                return o
            },
        ]
    }

    /// `PhaseGoals` for every plan × phase — `Programs.goals`, resolved.
    static func phaseGoalRows() -> [(plan: String, phase: ProgramPhase, g: PhaseGoals)] {
        Programs.all.flatMap { p in ProgramPhase.allCases.map { (p.id, $0, Programs.goals(planId: p.id, phase: $0)) } }
    }

    // MARK: - The dump

    static func seedSQL() throws -> String {
        let index = ExerciseIndex(catalogue)
        var out: [String] = []
        func line(_ s: String) { out.append(s) }

        line("""
        -- ─────────────────────────────────────────────────────────────────────────────
        -- W2 · THE FOUNDER'S SEED — paste AFTER `w2-generic-model.sql`.
        --
        -- GENERATED by `SeedDumpTests` (native/Packages/OnyxData/Tests) from the Swift
        -- constants this wave deletes: `Program.all`, `Phases.all`, `Levers.all` +
        -- `Levers.schedule`, `Programs.cutTargets` / `.bulkTargets`, `PhaseGoals`,
        -- `PrTruth.floor(for:)` and `Supplements.protocolSeed`. Not one number below
        -- was typed by hand; the rows ARE the constants, so the app reads the same
        -- deck, targets, phase, lever, stack and PR floors the day after as the day
        -- before.
        --
        -- SCOPED TO ONE ACCOUNT. Every statement names the founder's user_id. The
        -- second account (created 2026-09-08) is a fresh user and gets nothing here;
        -- W5's onboarding seeds a new user from `plan-templates.json` instead.
        --
        -- IDEMPOTENT, AND IT NEVER OVERWRITES AN EDIT. Inserts are `on conflict do
        -- nothing` or `where not exists`; the two tables that already hold founder
        -- rows (`plan_phase_goals`, `target_profiles`) are merged with `coalesce`, so
        -- a figure the founder changed in the app (the cut is 1,935 kcal / 190 g C in
        -- the row, not the constant's 1,955 / 195) stays what they made it, and only
        -- a NULL column takes the constant's value. `custom_supplements` are inserted
        -- only where the item key is absent — all nine already exist, and the live
        -- L-Citrulline dose (6 g) differs from the seed's (3 g) on purpose. Do not
        -- turn that into `on conflict do update`.
        --
        -- PR FLOORS are `PrTruth.floor(for:)` — the book's excess over what Onyx's own
        -- history already reached, NOT the raw book — written as `personal_records`
        -- rows with no session, and only where they exceed the row already there.
        -- ─────────────────────────────────────────────────────────────────────────────

        begin;

        """)

        // ── plans ────────────────────────────────────────────────────────────
        line("-- ── 1 · plans — the picker's three entries ─────────────────────────────────")
        for p in plans {
            line("""
            update public.plans
               set name = \(q(p.label)), blurb = \(q(p.blurb)), is_legacy = \(b(p.isLegacy)), sort = \(p.sort),
                   started_on = coalesce(started_on, \(q(p.startedOn)))
             where user_id = \(me) and program_id = \(q(p.id));
            insert into public.plans (user_id, name, program_id, active, started_on, blurb, is_legacy, sort)
            select \(me), \(q(p.label)), \(q(p.id)), false, \(q(p.startedOn)), \(q(p.blurb)), \(b(p.isLegacy)), \(p.sort)
             where not exists (select 1 from public.plans where user_id = \(me) and program_id = \(q(p.id)));
            """)
        }

        // ── routines ─────────────────────────────────────────────────────────
        line("\n-- ── 2 · routines — the three decks, one row per program day ────────────────")
        for program in Program.all {
            for (i, day) in program.days.enumerated() {
                let payload = try json(self.payload(day, index: index))
                line("""
                insert into public.routines (user_id, program_id, day_key, label, sub, weekday, accent, sort, payload)
                values (\(me), \(q(program.id)), \(q(day.key)), \(q(day.label)), \(q(day.sub)), \(day.weekday), \(day.accent), \(i),
                        \(q(payload))::jsonb)
                on conflict (user_id, program_id, day_key) do nothing;
                """)
            }
        }

        // ── plan_phases ──────────────────────────────────────────────────────
        line("\n-- ── 3 · plan_phases — the eight dated blocks ───────────────────────────────")
        for ph in Phases.all {
            let planId = ph.era == .ppl ? "ppl" : "onyx5"
            line("""
            insert into public.plan_phases (user_id, plan_id, start, kind, name, short, weeks, numbered, first_week, era, era_tag)
            values (\(me), \(q(planId)), \(q(ph.start)), \(q(ph.kind.rawValue)), \(q(ph.name)), \(q(ph.short)), \(ph.weeks), \(b(ph.numbered ?? false)), \(n(ph.firstWeek)), \(q(ph.era?.rawValue)), \(q(ph.eraTag)))
            on conflict (user_id, plan_id, start) do nothing;
            """)
        }

        // ── target_profiles (the rungs) ──────────────────────────────────────
        line("\n-- ── 4 · target_profiles — the ladder's rungs, as profiles with a kind ──────")
        for (i, lever) in Levers.all.enumerated() {
            line("""
            insert into public.target_profiles (user_id, key, label, summary, sort, kcal, protein_g, carbs_g, fat_g, steps_goal, kind)
            values (\(me), \(q(lever.id.rawValue)), \(q(lever.label)), \(q(lever.summary)), \(10 + i), \(n(lever.calorieGoal)), \(n(lever.proteinGoalG)), \(n(lever.carbsGoalG)), \(n(lever.fatGoalG)), \(n(lever.stepsGoal)), \(q(lever.kind.rawValue)))
            on conflict (user_id, key) do update set kind = excluded.kind;
            """)
        }

        // ── lever_periods ────────────────────────────────────────────────────
        line("\n-- ── 5 · lever_periods — when each rung came into force ─────────────────────")
        for period in Levers.schedule {
            let key: String? = period.leverId == .custom ? nil : period.leverId.rawValue
            let goals: String = try period.goals.map { g in
                try json(compact([
                    "calorie": g.calorie, "protein": g.protein, "carbs": g.carbs, "fat": g.fat, "steps": g.steps,
                ]))
            } ?? "null"
            line("""
            insert into public.lever_periods (user_id, starts_on, profile_key, goals)
            values (\(me), \(q(period.from)), \(q(key)), \(goals == "null" ? "null" : q(goals) + "::jsonb"))
            on conflict (user_id, starts_on) do nothing;
            """)
        }

        // ── plan_phase_goals ─────────────────────────────────────────────────
        line("\n-- ── 6 · plan_phase_goals — merged: a NULL column takes the constant, an edit stays ──")
        for row in phaseGoalRows() {
            let g = row.g
            line("""
            insert into public.plan_phase_goals (user_id, plan_id, phase, label, kcal, protein_g, carbs_g, fat_g, fiber_g, fiber_min, fiber_max, steps_goal,
                                                 target_weight_kg, target_body_fat_pct, target_muscle_mass_kg, rate_min_kg_wk, rate_max_kg_wk, body_fat_ceiling_pct)
            values (\(me), \(q(row.plan)), \(q(row.phase.rawValue)), \(q(g.label)), \(n(g.calorieGoal)), \(n(g.proteinGoalG)), \(n(g.carbsGoalG)), \(n(g.fatGoalG)), \(n(g.fiberGoalG)), \(n(g.fiberMin)), \(n(g.fiberMax)), \(n(g.stepsGoal)),
                    \(n(g.targetWeightKg)), \(n(g.targetBodyFatPct)), \(n(g.targetMuscleMassKg)), \(n(g.rateMinKgWk)), \(n(g.rateMaxKgWk)), \(n(g.bodyFatCeilingPct)))
            on conflict (user_id, plan_id, phase) do update set
              label = coalesce(plan_phase_goals.label, excluded.label),
              kcal = coalesce(plan_phase_goals.kcal, excluded.kcal),
              protein_g = coalesce(plan_phase_goals.protein_g, excluded.protein_g),
              carbs_g = coalesce(plan_phase_goals.carbs_g, excluded.carbs_g),
              fat_g = coalesce(plan_phase_goals.fat_g, excluded.fat_g),
              fiber_g = coalesce(plan_phase_goals.fiber_g, excluded.fiber_g),
              fiber_min = coalesce(plan_phase_goals.fiber_min, excluded.fiber_min),
              fiber_max = coalesce(plan_phase_goals.fiber_max, excluded.fiber_max),
              steps_goal = coalesce(plan_phase_goals.steps_goal, excluded.steps_goal),
              target_weight_kg = coalesce(plan_phase_goals.target_weight_kg, excluded.target_weight_kg),
              target_body_fat_pct = coalesce(plan_phase_goals.target_body_fat_pct, excluded.target_body_fat_pct),
              target_muscle_mass_kg = coalesce(plan_phase_goals.target_muscle_mass_kg, excluded.target_muscle_mass_kg),
              rate_min_kg_wk = coalesce(plan_phase_goals.rate_min_kg_wk, excluded.rate_min_kg_wk),
              rate_max_kg_wk = coalesce(plan_phase_goals.rate_max_kg_wk, excluded.rate_max_kg_wk),
              body_fat_ceiling_pct = coalesce(plan_phase_goals.body_fat_ceiling_pct, excluded.body_fat_ceiling_pct);
            """)
        }

        // ── plan_phase_volume ────────────────────────────────────────────────
        line("\n-- ── 7 · plan_phase_volume — the weekly set targets, per plan and phase ─────")
        line("insert into public.plan_phase_volume (user_id, plan_id, phase, muscle, target_sets) values")
        var volumeRows: [String] = []
        for p in Programs.all {
            for phase in ProgramPhase.allCases {
                let targets = Programs.weeklySetTargets(phase)
                for m in LandmarkMuscle.allCases {
                    volumeRows.append("  (\(me), \(q(p.id)), \(q(phase.rawValue)), \(q(m.rawValue)), \(Int(targets[m] ?? 0)))")
                }
            }
        }
        line(volumeRows.joined(separator: ",\n"))
        line("on conflict (user_id, plan_id, phase, muscle) do nothing;")

        // ── personal_records floors ──────────────────────────────────────────
        line("\n-- ── 8 · personal_records — the asserted floors, netted, session-less ────────")
        line("-- `achieved_on` is the book's date. A row only moves UP: an axis Onyx has since beaten keeps its record.")
        for name in PrTruth.book.keys.sorted() {
            guard let floor = PrTruth.floor(for: name) else { continue }
            let timed = TimedExercise.isTimed(name)
            let book = PrTruth.book[name]
            var rows: [(axis: String, value: Double, reps: Double?, kg: Double?)] = []
            if let w = floor.weight { rows.append(("weight", w, nil, w)) }
            if let e = floor.e1rm { rows.append(("e1rm", e, book?.setVolume?.reps, book?.setVolume?.kg)) }
            if let v = floor.volume { rows.append(("volume", v, book?.setVolume?.reps, book?.setVolume?.kg)) }
            if let r = floor.reps { rows.append(("reps", r, r, 0)) }
            if timed, let s = floor.seconds { rows.append(("reps", s, s, 0)) }
            for r in rows {
                line("""
                insert into public.personal_records (user_id, exercise_key, axis, value, reps, weight_kg, session_id, achieved_on)
                values (\(me), \(q(name)), \(q(r.axis)), \(n(r.value)), \(n(r.reps.map { Int($0) })), \(n(r.kg)), null, \(q(PrTruth.asOf)))
                on conflict (user_id, exercise_key, axis) do update set
                  value = excluded.value, reps = excluded.reps, weight_kg = excluded.weight_kg,
                  session_id = null, achieved_on = excluded.achieved_on
                where personal_records.value < excluded.value;
                """)
            }
        }

        // ── custom_supplements ───────────────────────────────────────────────
        line("\n-- ── 9 · custom_supplements — the seed, only where an item key is absent ────")
        for slot in Supplements.protocolSeed {
            for item in slot.items {
                let schedule = try json(compact([
                    "key": item.key, "slot": slot.label, "notes": item.notes, "trainingOnly": item.trainingOnly,
                ]))
                line("""
                insert into public.custom_supplements (user_id, name, dose, color, time, schedule)
                select \(me), \(q(item.name)), \(q(item.dose)), \(q(slot.accent)), \(q(slot.time)), \(q(schedule))::jsonb
                 where not exists (select 1 from public.custom_supplements
                                    where user_id = \(me) and schedule->>'key' = \(q(item.key)));
                """)
            }
        }

        // ── exercises.slug overrides ─────────────────────────────────────────
        line("\n-- ── 10 · exercises.slug — where a deck spells a movement differently from its catalogue row ──")
        var overrides = 0
        var seen = Set<String>()
        for program in Program.all {
            for e in program.days.flatMap(\.exercises) where !seen.contains(e.name) {
                seen.insert(e.name)
                let slug = ExerciseSlug.id(e.name)
                guard let id = try? index.id(forName: e.name),
                      let row = catalogue.first(where: { $0.id == id }),
                      ExerciseSlug.id(row.name) != slug
                else { continue }
                overrides += 1
                line("""
                update public.exercises set slug = null where user_id = \(me) and slug = \(q(slug)) and id <> \(q(id))::uuid;
                update public.exercises set slug = \(q(slug)) where id = \(q(id))::uuid;
                """)
            }
        }
        if overrides == 0 {
            line("-- none: every deck movement's name matches its catalogue row exactly, so the DDL's backfill already wrote the right slug.")
        }

        line("""

        commit;

        -- ── VERIFY ───────────────────────────────────────────────────────────────────
        select 'plans' as t, count(*) from public.plans where user_id = \(me)
        union all select 'routines', count(*) from public.routines where user_id = \(me)
        union all select 'plan_phases', count(*) from public.plan_phases where user_id = \(me)
        union all select 'lever_periods', count(*) from public.lever_periods where user_id = \(me)
        union all select 'target_profiles (rungs)', count(*) from public.target_profiles where user_id = \(me) and kind <> 'day'
        union all select 'plan_phase_goals', count(*) from public.plan_phase_goals where user_id = \(me)
        union all select 'plan_phase_volume', count(*) from public.plan_phase_volume where user_id = \(me)
        union all select 'personal_records (floors)', count(*) from public.personal_records where user_id = \(me) and session_id is null
        union all select 'exercises with slug', count(*) from public.exercises where user_id = \(me) and slug is not null
        union all select 'other account rows', (
          select count(*) from public.routines where user_id = '\(otherAccount)')
          + (select count(*) from public.plan_phases where user_id = '\(otherAccount)')
          + (select count(*) from public.lever_periods where user_id = '\(otherAccount)');
        -- Expect: plans 3 · routines 14 · plan_phases 8 · lever_periods 5 · rungs 4 · plan_phase_goals 6 ·
        --         plan_phase_volume 96 · floors ≥ 12 · slugs 46 · other account 0.
        """)

        return out.joined(separator: "\n") + "\n"
    }

    /// The same decks as a bundled resource for W5's onboarding — the template a
    /// NEW user picks from. Data, not code: it lives in the app bundle, not in
    /// OnyxCore.
    static func templatesJSON() throws -> String {
        let index = ExerciseIndex(catalogue)
        let plans: [[String: Any]] = self.plans.map { p in
            let program = Program.byId(p.id)
            var goals: [String: Any] = [:]
            for phase in ProgramPhase.allCases {
                let g = Programs.goals(planId: p.id, phase: phase)
                goals[phase.rawValue] = compact([
                    "label": g.label, "kcal": g.calorieGoal, "proteinG": g.proteinGoalG, "carbsG": g.carbsGoalG,
                    "fatG": g.fatGoalG, "fiberG": g.fiberGoalG, "fiberMin": g.fiberMin, "fiberMax": g.fiberMax,
                    "stepsGoal": g.stepsGoal, "targetWeightKg": g.targetWeightKg, "targetBodyFatPct": g.targetBodyFatPct,
                    "targetMuscleMassKg": g.targetMuscleMassKg, "rateMinKgWk": g.rateMinKgWk, "rateMaxKgWk": g.rateMaxKgWk,
                    "bodyFatCeilingPct": g.bodyFatCeilingPct,
                ])
            }
            var volume: [String: Any] = [:]
            for phase in ProgramPhase.allCases {
                volume[phase.rawValue] = Dictionary(uniqueKeysWithValues: Programs.weeklySetTargets(phase).map { ($0.key.rawValue, Int($0.value)) })
            }
            return [
                "id": p.id, "label": p.label, "blurb": p.blurb, "isLegacy": p.isLegacy, "sort": p.sort,
                "days": (program?.days ?? []).enumerated().map { i, d -> [String: Any] in
                    var o: [String: Any] = [
                        "key": d.key, "label": d.label, "weekday": d.weekday, "accent": Int(d.accent), "sort": i,
                        "exercises": (payload(d, index: index)["exercises"] as? [[String: Any]] ?? []).map { e in
                            // A template carries no catalogue uuid: the new user's
                            // catalogue is inserted at onboarding and resolved by name.
                            var e = e; e["exerciseId"] = nil; return e
                        },
                    ]
                    if let sub = d.sub { o["sub"] = sub }
                    return o
                },
                "phaseGoals": goals,
                "volumeTargets": volume,
            ]
        }
        let data = try JSONSerialization.data(
            withJSONObject: ["version": 1, "plans": plans], options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        )
        return String(decoding: data, as: UTF8.self) + "\n"
    }

    // MARK: - Tests

    @Test("every statement is the founder's, and the second account gets nothing")
    func scoped() throws {
        let sql = try Self.seedSQL()
        // Statements end at a line break; a semicolon inside a blurb is prose.
        let statements = sql.components(separatedBy: ";\n")
            .filter { $0.contains("insert into") || $0.contains("update public.") }
        #expect(!statements.isEmpty)
        for s in statements {
            #expect(s.contains(Self.founder), "unscoped statement: \(s.prefix(120))")
        }
        // The other account appears only in the verify block, as a zero to expect.
        let body = sql.components(separatedBy: "-- ── VERIFY").first ?? ""
        #expect(!body.contains(Self.otherAccount))
    }

    @Test("the deck resolves every Onyx-5 movement to a catalogue uuid")
    func onyx5Resolves() throws {
        let index = ExerciseIndex(Self.catalogue)
        for day in Program.onyx5.days {
            let payload = Self.payload(day, index: index)
            let exercises = payload["exercises"] as? [[String: Any]] ?? []
            #expect(exercises.count == day.exercises.count)
            for e in exercises {
                #expect(e["exerciseId"] != nil, "\(e["name"] ?? "?") has no catalogue row")
            }
        }
    }

    @Test("writes the seed when asked to")
    func dump() throws {
        let env = ProcessInfo.processInfo.environment
        if let out = env["ONYX_SEED_OUT"] {
            try Self.seedSQL().write(toFile: out, atomically: true, encoding: .utf8)
        }
        if let out = env["ONYX_TEMPLATES_OUT"] {
            try Self.templatesJSON().write(toFile: out, atomically: true, encoding: .utf8)
        }
    }
}
