// GENERATED by scripts/gen-atlas-swift.mjs — DO NOT EDIT.
//
// The anatomy lives in src/lib/body/atlas.ts and is emitted here because
// SwiftUI cannot parse an SVG path. `atlas-parity.test.ts` re-runs the
// generator and fails when this file differs, so the app and the widget can
// never disagree about where a muscle is.
//
// Coordinates are on the atlas's 120 x 260 viewBox and are scaled into
// whatever rect the shape is given, preserving aspect ratio and centring.
import SwiftUI

enum HelixAtlasView: String {
  case front, back
}

struct HelixAtlasPath: Identifiable {
  let muscle: String
  let view: HelixAtlasView
  let build: (CGRect, inout Path) -> Void

  var id: String { "\(muscle)-\(view.rawValue)-\(String(describing: build))" }

  init(muscle: String, view: HelixAtlasView, _ build: @escaping (CGRect, inout Path) -> Void) {
    self.muscle = muscle
    self.view = view
    self.build = build
  }
}

enum HelixAtlas {
  static let viewBox = CGSize(width: 120, height: 260)

  /// Head, neck and feet: anatomy, never data, never tinted.
  static let base: [(CGRect, inout Path) -> Void] = [
  { rect, p in
    p.move(to: pt(60, 8, in: rect))
    p.addCurve(to: pt(74, 22, in: rect), control1: pt(67.7, 8, in: rect), control2: pt(74, 14.3, in: rect))
    p.addCurve(to: pt(60, 36, in: rect), control1: pt(74, 29.7, in: rect), control2: pt(67.7, 36, in: rect))
    p.addCurve(to: pt(46, 22, in: rect), control1: pt(52.3, 36, in: rect), control2: pt(46, 29.7, in: rect))
    p.addCurve(to: pt(60, 8, in: rect), control1: pt(46, 14.3, in: rect), control2: pt(52.3, 8, in: rect))
    p.closeSubpath()
  },
  { rect, p in
    p.move(to: pt(53, 35, in: rect))
    p.addLine(to: pt(67, 35, in: rect))
    p.addLine(to: pt(67, 45, in: rect))
    p.addLine(to: pt(53, 45, in: rect))
    p.closeSubpath()
  },
  { rect, p in
    p.move(to: pt(43, 240, in: rect))
    p.addLine(to: pt(53, 240, in: rect))
    p.addLine(to: pt(54, 251, in: rect))
    p.addLine(to: pt(42, 251, in: rect))
    p.closeSubpath()
  },
  { rect, p in
    p.move(to: pt(77, 240, in: rect))
    p.addLine(to: pt(67, 240, in: rect))
    p.addLine(to: pt(66, 251, in: rect))
    p.addLine(to: pt(78, 251, in: rect))
    p.closeSubpath()
  },
  ]

  static let muscles: [HelixAtlasPath] = [
  HelixAtlasPath(muscle: "Side delts", view: .front) { rect, p in
    p.move(to: pt(38, 44, in: rect))
    p.addCurve(to: pt(20, 64, in: rect), control1: pt(28, 45, in: rect), control2: pt(21, 52, in: rect))
    p.addLine(to: pt(33, 69, in: rect))
    p.addCurve(to: pt(45, 51, in: rect), control1: pt(34, 58, in: rect), control2: pt(39, 53, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Side delts", view: .front) { rect, p in
    p.move(to: pt(82, 44, in: rect))
    p.addCurve(to: pt(100, 64, in: rect), control1: pt(92, 45, in: rect), control2: pt(99, 52, in: rect))
    p.addLine(to: pt(87, 69, in: rect))
    p.addCurve(to: pt(75, 51, in: rect), control1: pt(86, 58, in: rect), control2: pt(81, 53, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Chest", view: .front) { rect, p in
    p.move(to: pt(45, 50, in: rect))
    p.addLine(to: pt(75, 50, in: rect))
    p.addCurve(to: pt(83, 72, in: rect), control1: pt(82, 52, in: rect), control2: pt(84, 60, in: rect))
    p.addCurve(to: pt(60, 83, in: rect), control1: pt(76, 80, in: rect), control2: pt(66, 83, in: rect))
    p.addCurve(to: pt(37, 72, in: rect), control1: pt(54, 83, in: rect), control2: pt(44, 80, in: rect))
    p.addCurve(to: pt(45, 50, in: rect), control1: pt(36, 60, in: rect), control2: pt(38, 52, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Abs/core", view: .front) { rect, p in
    p.move(to: pt(42, 86, in: rect))
    p.addLine(to: pt(78, 86, in: rect))
    p.addCurve(to: pt(72, 132, in: rect), control1: pt(79, 102, in: rect), control2: pt(77, 118, in: rect))
    p.addLine(to: pt(48, 132, in: rect))
    p.addCurve(to: pt(42, 86, in: rect), control1: pt(43, 118, in: rect), control2: pt(41, 102, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Biceps", view: .front) { rect, p in
    p.move(to: pt(22, 68, in: rect))
    p.addCurve(to: pt(19, 107, in: rect), control1: pt(19, 80, in: rect), control2: pt(18, 94, in: rect))
    p.addLine(to: pt(31, 105, in: rect))
    p.addCurve(to: pt(34, 72, in: rect), control1: pt(31, 92, in: rect), control2: pt(33, 80, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Biceps", view: .front) { rect, p in
    p.move(to: pt(98, 68, in: rect))
    p.addCurve(to: pt(101, 107, in: rect), control1: pt(101, 80, in: rect), control2: pt(102, 94, in: rect))
    p.addLine(to: pt(89, 105, in: rect))
    p.addCurve(to: pt(86, 72, in: rect), control1: pt(89, 92, in: rect), control2: pt(87, 80, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Forearms", view: .front) { rect, p in
    p.move(to: pt(19, 109, in: rect))
    p.addCurve(to: pt(27, 147, in: rect), control1: pt(19, 122, in: rect), control2: pt(21, 136, in: rect))
    p.addLine(to: pt(35, 144, in: rect))
    p.addCurve(to: pt(30, 107, in: rect), control1: pt(31, 134, in: rect), control2: pt(29, 121, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Forearms", view: .front) { rect, p in
    p.move(to: pt(101, 109, in: rect))
    p.addCurve(to: pt(93, 147, in: rect), control1: pt(101, 122, in: rect), control2: pt(99, 136, in: rect))
    p.addLine(to: pt(85, 144, in: rect))
    p.addCurve(to: pt(90, 107, in: rect), control1: pt(89, 134, in: rect), control2: pt(91, 121, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Quads", view: .front) { rect, p in
    p.move(to: pt(43, 133, in: rect))
    p.addCurve(to: pt(40, 189, in: rect), control1: pt(38, 149, in: rect), control2: pt(37, 169, in: rect))
    p.addLine(to: pt(53, 189, in: rect))
    p.addCurve(to: pt(58, 135, in: rect), control1: pt(55, 171, in: rect), control2: pt(56, 151, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Quads", view: .front) { rect, p in
    p.move(to: pt(77, 133, in: rect))
    p.addCurve(to: pt(80, 189, in: rect), control1: pt(82, 149, in: rect), control2: pt(83, 169, in: rect))
    p.addLine(to: pt(67, 189, in: rect))
    p.addCurve(to: pt(62, 135, in: rect), control1: pt(65, 171, in: rect), control2: pt(64, 151, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Adductors", view: .front) { rect, p in
    p.move(to: pt(55, 136, in: rect))
    p.addCurve(to: pt(58, 178, in: rect), control1: pt(56, 152, in: rect), control2: pt(57, 166, in: rect))
    p.addLine(to: pt(60, 178, in: rect))
    p.addCurve(to: pt(59, 136, in: rect), control1: pt(60, 160, in: rect), control2: pt(60, 146, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Adductors", view: .front) { rect, p in
    p.move(to: pt(65, 136, in: rect))
    p.addCurve(to: pt(62, 178, in: rect), control1: pt(64, 152, in: rect), control2: pt(63, 166, in: rect))
    p.addLine(to: pt(60, 178, in: rect))
    p.addCurve(to: pt(61, 136, in: rect), control1: pt(60, 160, in: rect), control2: pt(60, 146, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Calves", view: .front) { rect, p in
    p.move(to: pt(41, 193, in: rect))
    p.addCurve(to: pt(43, 240, in: rect), control1: pt(40, 209, in: rect), control2: pt(41, 227, in: rect))
    p.addLine(to: pt(53, 240, in: rect))
    p.addCurve(to: pt(53, 193, in: rect), control1: pt(54, 224, in: rect), control2: pt(54, 207, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Calves", view: .front) { rect, p in
    p.move(to: pt(79, 193, in: rect))
    p.addCurve(to: pt(77, 240, in: rect), control1: pt(80, 209, in: rect), control2: pt(79, 227, in: rect))
    p.addLine(to: pt(67, 240, in: rect))
    p.addCurve(to: pt(67, 193, in: rect), control1: pt(66, 224, in: rect), control2: pt(66, 207, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Rear delts", view: .back) { rect, p in
    p.move(to: pt(38, 44, in: rect))
    p.addCurve(to: pt(20, 64, in: rect), control1: pt(28, 45, in: rect), control2: pt(21, 52, in: rect))
    p.addLine(to: pt(33, 69, in: rect))
    p.addCurve(to: pt(45, 51, in: rect), control1: pt(34, 58, in: rect), control2: pt(39, 53, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Rear delts", view: .back) { rect, p in
    p.move(to: pt(82, 44, in: rect))
    p.addCurve(to: pt(100, 64, in: rect), control1: pt(92, 45, in: rect), control2: pt(99, 52, in: rect))
    p.addLine(to: pt(87, 69, in: rect))
    p.addCurve(to: pt(75, 51, in: rect), control1: pt(86, 58, in: rect), control2: pt(81, 53, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Back", view: .back) { rect, p in
    p.move(to: pt(45, 50, in: rect))
    p.addLine(to: pt(75, 50, in: rect))
    p.addCurve(to: pt(84, 81, in: rect), control1: pt(83, 53, in: rect), control2: pt(86, 64, in: rect))
    p.addCurve(to: pt(60, 107, in: rect), control1: pt(80, 97, in: rect), control2: pt(72, 105, in: rect))
    p.addCurve(to: pt(36, 81, in: rect), control1: pt(48, 105, in: rect), control2: pt(40, 97, in: rect))
    p.addCurve(to: pt(45, 50, in: rect), control1: pt(34, 64, in: rect), control2: pt(37, 53, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Triceps", view: .back) { rect, p in
    p.move(to: pt(22, 68, in: rect))
    p.addCurve(to: pt(19, 107, in: rect), control1: pt(19, 80, in: rect), control2: pt(18, 94, in: rect))
    p.addLine(to: pt(31, 105, in: rect))
    p.addCurve(to: pt(34, 72, in: rect), control1: pt(31, 92, in: rect), control2: pt(33, 80, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Triceps", view: .back) { rect, p in
    p.move(to: pt(98, 68, in: rect))
    p.addCurve(to: pt(101, 107, in: rect), control1: pt(101, 80, in: rect), control2: pt(102, 94, in: rect))
    p.addLine(to: pt(89, 105, in: rect))
    p.addCurve(to: pt(86, 72, in: rect), control1: pt(89, 92, in: rect), control2: pt(87, 80, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Forearms", view: .back) { rect, p in
    p.move(to: pt(19, 109, in: rect))
    p.addCurve(to: pt(27, 147, in: rect), control1: pt(19, 122, in: rect), control2: pt(21, 136, in: rect))
    p.addLine(to: pt(35, 144, in: rect))
    p.addCurve(to: pt(30, 107, in: rect), control1: pt(31, 134, in: rect), control2: pt(29, 121, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Forearms", view: .back) { rect, p in
    p.move(to: pt(101, 109, in: rect))
    p.addCurve(to: pt(93, 147, in: rect), control1: pt(101, 122, in: rect), control2: pt(99, 136, in: rect))
    p.addLine(to: pt(85, 144, in: rect))
    p.addCurve(to: pt(90, 107, in: rect), control1: pt(89, 134, in: rect), control2: pt(91, 121, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Glutes", view: .back) { rect, p in
    p.move(to: pt(43, 109, in: rect))
    p.addCurve(to: pt(41, 141, in: rect), control1: pt(37, 117, in: rect), control2: pt(36, 131, in: rect))
    p.addCurve(to: pt(59, 140, in: rect), control1: pt(48, 146, in: rect), control2: pt(55, 145, in: rect))
    p.addLine(to: pt(59, 109, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Glutes", view: .back) { rect, p in
    p.move(to: pt(77, 109, in: rect))
    p.addCurve(to: pt(79, 141, in: rect), control1: pt(83, 117, in: rect), control2: pt(84, 131, in: rect))
    p.addCurve(to: pt(61, 140, in: rect), control1: pt(72, 146, in: rect), control2: pt(65, 145, in: rect))
    p.addLine(to: pt(61, 109, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Hamstrings", view: .back) { rect, p in
    p.move(to: pt(41, 145, in: rect))
    p.addCurve(to: pt(41, 190, in: rect), control1: pt(38, 161, in: rect), control2: pt(38, 177, in: rect))
    p.addLine(to: pt(54, 190, in: rect))
    p.addCurve(to: pt(58, 145, in: rect), control1: pt(55, 175, in: rect), control2: pt(56, 159, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Hamstrings", view: .back) { rect, p in
    p.move(to: pt(79, 145, in: rect))
    p.addCurve(to: pt(79, 190, in: rect), control1: pt(82, 161, in: rect), control2: pt(82, 177, in: rect))
    p.addLine(to: pt(66, 190, in: rect))
    p.addCurve(to: pt(62, 145, in: rect), control1: pt(65, 175, in: rect), control2: pt(64, 159, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Calves", view: .back) { rect, p in
    p.move(to: pt(42, 194, in: rect))
    p.addCurve(to: pt(44, 237, in: rect), control1: pt(40, 209, in: rect), control2: pt(41, 226, in: rect))
    p.addLine(to: pt(54, 237, in: rect))
    p.addCurve(to: pt(54, 194, in: rect), control1: pt(55, 223, in: rect), control2: pt(55, 207, in: rect))
    p.closeSubpath()
  },
  HelixAtlasPath(muscle: "Calves", view: .back) { rect, p in
    p.move(to: pt(78, 194, in: rect))
    p.addCurve(to: pt(76, 237, in: rect), control1: pt(80, 209, in: rect), control2: pt(79, 226, in: rect))
    p.addLine(to: pt(66, 237, in: rect))
    p.addCurve(to: pt(66, 194, in: rect), control1: pt(65, 223, in: rect), control2: pt(65, 207, in: rect))
    p.closeSubpath()
  },
  ]

  /// One viewBox point, scaled into `rect` with the aspect ratio preserved.
  ///
  /// Fitting WITHOUT preserving it is what turns a body into a puddle in a wide
  /// widget cell — and every muscle would still be in the right place relative
  /// to the others, so it would look deliberate.
  static func pt(_ x: CGFloat, _ y: CGFloat, in rect: CGRect) -> CGPoint {
    let scale = min(rect.width / viewBox.width, rect.height / viewBox.height)
    let dx = rect.minX + (rect.width - viewBox.width * scale) / 2
    let dy = rect.minY + (rect.height - viewBox.height * scale) / 2
    return CGPoint(x: dx + x * scale, y: dy + y * scale)
  }
}

private func pt(_ x: CGFloat, _ y: CGFloat, in rect: CGRect) -> CGPoint {
  HelixAtlas.pt(x, y, in: rect)
}
